### ISSUE TITLE
ReadMe里头的ProGuard内容是不是颠倒了？

### ISSUE THREAD

**Issue by tianzry** [zhihu/Matisse#103]
原文如下显示：

## ProGuard

If you use Glide as your image engine, add rules as Glide's README says.
And add extra rule:
```
-dontwarn com.squareup.picasso.**
```
If you use Picasso as your image engine, add rules as Picasso's README says.
And add extra rule:
```
-dontwarn com.bumptech.glide.**
```
新手尝试用这个库，说错勿喷

**Comment by gejiaheng** [comment]
It's not. See https://github.com/zhihu/Matisse/pull/102.
