### ISSUE TITLE
这个添加compile 'com.zhihu.android:matisse:0.4.3'的和你们demo的不一样啊

### ISSUE THREAD

**Issue by wudaotiantian** [zhihu/Matisse#105]
1 没有IncapableCause这个类
2Matisse.obtainPathResult(data)获取图片的返回路径的这个方法也没有看到，只有uri的方法

**Comment by gejiaheng** [comment]
Check out our v0.5.0 alpha releases: https://github.com/zhihu/Matisse/releases
