### ISSUE TITLE
框架如何将视频等文件不显示在列表中

### ISSUE THREAD

**Issue by wudaotiantian** [zhihu/Matisse#108]

**Comment by gejiaheng** [comment]
See https://github.com/zhihu/Matisse/wiki/Basic-Usage#mime-type
And don't forget to use the latest alpha release (https://github.com/zhihu/Matisse/releases).

**Comment by wudaotiantian** [comment]
那我就搞不懂那选择单独的文件类型的意义何在，提示一句不支持的文件类型，不如做成不显示

**Comment by gejiaheng** [comment]
There are different features requested by different developers, we can't simply not satisfy everyone.  And this is an open source project, I can't control everything.
