### ISSUE TITLE
拍照的图片保存地址是哪里，可以设置吗？

### ISSUE THREAD

**Issue by 3kqing** [zhihu/Matisse#109]
拍照的图片保存地址是哪里，可以设置吗？

**Comment by 3kqing** [comment]
看到了，好像默认的是 DIRECTORY_DCIM，能不能自定义呢？

**Comment by fuyoutianxia** [comment]
你好，请问这个问题你解决了么，我拍照的图片保存到了根目录下，想修改路径

**Comment by gejiaheng** [comment]
@3kqing We don't have customization interface for this. You can send a pull request.
