### ISSUE TITLE
为什么在选择图片的时候会显示应用的标题栏？

### ISSUE THREAD

**Issue by 838514984** [zhihu/Matisse#117]
但是用Demo不会有这个问题，不知道是在那设置的。。

**Comment by 838514984** [comment]
找到了，应该是在BasePreviewActivity中setTheme(SelectionSpec.getInstance().themeId);这句话的原因
在demo项目中有这句话，在自己添加的依赖项目中没有、

**Comment by fuyoutianxia** [comment]
兄弟，这个类没法改啊，你是把demo里的类都复制过去的么

**Comment by gejiaheng** [comment]
@838514984 Would you please post a screenshot? I don't exactly know what your issue is.

**Comment by 838514984** [comment]
@gejiaheng 
i hvae used <item name="windowNoTitle">true</item> <item name="windowActionBar">false</item> to solve this problem.

**Comment by 838514984** [comment]
windowNoTitle true,windowActionBar false
