### ISSUE TITLE
OPPO R9 点击拍照崩溃

### ISSUE THREAD

**Issue by huohuoyoyo** [zhihu/Matisse#120]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference

**Comment by xiang473535976** [comment]
@huohuoyoyo   请问你是怎么解决的 我也遇到了这个问题

**Comment by huohuoyoyo** [comment]
在清单文件中配置
<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="包名.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>

然后在res文件夹中新建xml文件夹 然后新建provider_paths 文件
<resources xmlns:android="http://schemas.android.com/apk/res/android">
  
    <paths>
        <external-path
            name="my_images"
            path="Pictures"/>
    </paths>
</resources>
