### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by bravekingzhang** [zhihu/Matisse#122]
java.lang.NoSuchMethodError: No virtual method load(Landroid/net/Uri;)Lcom/bumptech/glide/DrawableTypeRequest;

目测是  glide  4.0.0-RC1 版本中已经移除了这个方法

**Comment by flamezheng** [comment]
一样的问题，换成3.7.0解决该问题。
ps:没有在readme中提示使用glide

**Comment by gejiaheng** [comment]
So, do we need to bump Glide to v4.0.0?

**Comment by faketon** [comment]
not support glide 4.0.0-RC1 ???

**Comment by bravekingzhang** [comment]
Glide4.0.0有不少的优化，建议支持。
