### ISSUE TITLE
图片多选，视频单选

### ISSUE THREAD

**Issue by cwyrzz** [zhihu/Matisse#125]
MimeType.allOf() 的时候，是否可以做到图片多选，视频单选

**Comment by teprinciple** [comment]
@cwyrzz 我现在也要实现图片多选，视频单选。你找到解决方法了吗？

**Comment by cwyrzz** [comment]
没用这个库了，都不维护的

**Comment by gejiaheng** [comment]
@cwyrzz It's OK. I've had some personal issues in the past month. Sorry for that.

**Comment by gejiaheng** [comment]
@cwyrzz @teprinciple Matisse doesn't support your requested feature. But a PR is always welcome.

**Comment by helloV7** [comment]
复制一份 AlbumMediaAdapter
在 修改onCheckViewClicked
原本：
`public void onCheckViewClicked(CheckView checkView, Item item, RecyclerView.ViewHolder holder) {
        if (mSelectionSpec.countable) {
            int checkedNum = mSelectedCollection.checkedNumOf(item);
            if (checkedNum == CheckView.UNCHECKED) {
                if (assertAddSelection(holder.itemView.getContext(), item)) {
                    mSelectedCollection.add(item);
                    notifyCheckStateChanged();
                }
            } else {
                mSelectedCollection.remove(item);
                notifyCheckStateChanged();
            }
        } else {
            if (mSelectedCollection.isSelected(item)) {
                mSelectedCollection.remove(item);
                notifyCheckStateChanged();
            } else {
                if (assertAddSelection(holder.itemView.getContext(), item)) {
                    mSelectedCollection.add(item);
                    notifyCheckStateChanged();
                }
            }
        }
    }`
改为：
` public void onCheckViewClicked(CheckView checkView, Item item, RecyclerView.ViewHolder holder) {



            if (mSelectionSpec.countable) {

            int checkedNum = mSelectedCollection.checkedNumOf(item);
            if (checkedNum == CheckView.UNCHECKED) {
                if (assertAddSelection(holder.itemView.getContext(), item)) {
                    mSelectedCollection.add(item);
                    notifyCheckStateChanged();
                }
            } else {
                mSelectedCollection.remove(item);
                notifyCheckStateChanged();
            }
        } else {
            if (mSelectedCollection.isSelected(item)) {
                mSelectedCollection.remove(item);
                notifyCheckStateChanged();
            } else {
                if (assertAddSelection(holder.itemView.getContext(), item)) {
                    mSelectedCollection.add(item);
                    notifyCheckStateChanged();
                }
            }
        }

        if (mSelectedCollection.isSelected(item)){
            if (item.isVideo() ){
                mSelectionSpec.maxSelectable = 1;
            }else {
                mSelectionSpec.maxSelectable = 9;
            }
            notifyCheckStateChanged();
        }
    }`
大致这样   将就着用
