### ISSUE TITLE
Add Capture with exception.

### ISSUE THREAD

**Issue by Pinned** [zhihu/Matisse#13]
![image](https://cloud.githubusercontent.com/assets/8403321/25313255/d96a3130-285d-11e7-9388-7d32117ff735.png)

![image](https://cloud.githubusercontent.com/assets/8403321/25313254/d0e05918-285d-11e7-818a-37117d466def.png)

**Comment by gejiaheng** [comment]
@Pinned 
Thanks for reporting this bug. https://github.com/zhihu/Matisse/pull/14 has been merged.
