### ISSUE TITLE
SquareFrameLayout这个类的作用

### ISSUE THREAD

**Issue by cornflower10** [zhihu/Matisse#130]
public class SquareFrameLayout extends FrameLayout {

    public SquareFrameLayout(Context context) {
        super(context);
    }

    public SquareFrameLayout(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        super.onMeasure(widthMeasureSpec, widthMeasureSpec);
    }
}
这个类没有任何操作为啥还要单独写出来，表示不懂？？

**Comment by cornflower10** [comment]
不好意思，看出来了是讲宽高设置一样

**Comment by Djwei** [comment]
你好,你知道Matisse 的获取图片路径地址是什么方法吗 我看之前的源码是有的  但是最新依赖的版本里面没有这个方法

**Comment by artshell** [comment]
@Djwei 源码里有个工具类叫 PathUtils，通过它获取就行了

**Comment by Djwei** [comment]
好的  我试试看能不能拿到，我直接自己拿到Uri 转换成path地址了 谢谢了🙏

**Comment by Djwei** [comment]
@artshell 好的 我试试看能不能拿到，我直接自己拿到Uri 转换成path地址了 谢谢了🙏

**Comment by Djwei** [comment]
好的 非常感谢  已经解决了  🙏
