### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by LeonXtp** [zhihu/Matisse#136]
No virtual method load(Landroid/net/Uri;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.andtest.leonxtp.androidtest-1/base.apk)

我使用的版本是
compile 'com.zhihu.android:matisse:0.4.3'
compile 'com.github.bumptech.glide:glide:4.0.0-RC1'
compile 'com.android.support:support-v4:25.3.1'
annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0-RC1'

**Comment by gejiaheng** [comment]
@LeonXtp Seems that Matisse is not compatible with Glide v4.0.0. I'll work on it. For now, you can use a v3.x.x for Glide dependency.
