### ISSUE TITLE
How to support for Fresco? 

### ISSUE THREAD

**Issue by xueyaolive** [zhihu/Matisse#141]

**Comment by lizhangqu** [comment]
see [一种使用Fresco非侵入式加载图片的方式](lizhangqu.github.io/2017/07/27/一种使用Fresco非侵入式加载图片的方式/)

**Comment by DancingDuck** [comment]
you need fouces about  the imageengine!!

**Comment by gejiaheng** [comment]
https://github.com/zhihu/Matisse/issues/119
