### ISSUE TITLE
ProGuard 写反了吧？ 请的临时工吧！！！

### ISSUE THREAD

**Issue by zhanaotian** [zhihu/Matisse#168]
ProGuard

If you use Glide as your image engine, add rules as Glide's README says.
And add extra rule:

-dontwarn com.squareup.picasso.**
If you use Picasso as your image engine, add rules as Picasso's README says.
And add extra rule:

-dontwarn com.bumptech.glide.**

**Comment by gejiaheng** [comment]
嗯，你说对了，我是临时工。

**Comment by NashLegend** [comment]
英语要勤加练习

**Comment by nekocode** [comment]
这是开源项目，没有人有义务为你服务，不要一幅高高在上的态度。其次，你确定你的水平能看懂这段 ProGuard 的用意？（请教问题请虚心，遇到问题多想想是不是自己的问题
