### ISSUE TITLE
请问我可以在启动Matisse时添加过滤条件吗?

### ISSUE THREAD

**Issue by VictoryWangV** [zhihu/Matisse#189]
首先,感谢您为我们提供如此优秀的框架;
正如标题所示,我想在启动启动Matisse的时候添加过滤条件,比如说不显示gif格式的图片,请问现在这个版本可以满足这个需求嘛?

**Comment by shisp** [comment]
以下代码应该可实现你的需求，可以验证下
Matisse.from(MainActivity.this)
                        .choose(MimeType.of(MimeType.JPEG, MimeType.PNG))
                        .showSingleMediaType(true)
                        .theme(R.style.Matisse_Dracula)
                        .countable(false)
                        .maxSelectable(9)
                        .imageEngine(new PicassoEngine())
                        .forResult(REQUEST_CODE_CHOOSE);

**Comment by VictoryWangV** [comment]
谢谢~

**Comment by AlbertLarry** [comment]
如题，增加一个条件，如果我想实现的是不显示大于5MB的gif格式图片怎么设置？可以实现吗？

**Comment by gejiaheng** [comment]
@AlbertLarry 
目前不支持。当前只支持某个格式显示与否，也就是 Gif 格式图片，要么都显示，要么都不显示。如果设置为 Gif 图片都显示，你可以继续通过 `Filter` 接口（类似 Sample 里的 GifSizeFilter）来控制用户能否选择某张 Gif 图片。

**Comment by only0315** [comment]
你好，如何设置不显示gif图片呢
