### ISSUE TITLE
请问 onActivityResult的时候，如何判断是拍照返回的还是选择图片返回的呢？

### ISSUE THREAD

**Issue by cxyhegithub** [zhihu/Matisse#195]
请问 onActivityResult的时候，如何判断是拍照返回的还是选择图片返回的呢？

**Comment by yinhaojun** [comment]
通过不同的requestCode判断吧

**Comment by gejiaheng** [comment]
@cxyhegithub See `MatisseActivity.onActivityResult()`, it has the code you want to know.
