### ISSUE TITLE
Support video files

### ISSUE THREAD

**Issue by Drizzlezhang** [zhihu/Matisse#2]
I have read source code of the repo, a beautiful project! And I think the library can support more feature , such as select video. So can I create a pull request? Because in your README:

> Better to open an issue to discuss with the team and the community if you're intended to work on something BIG.

**Comment by gejiaheng** [comment]
@Drizzlezhang 
Thanks for your enthusiasm. But sorry, this is a under development feature internally. I'll push the code in the next few days.
I appreciate it that we share the same recognition on this project. I'll add an enhancement tag for this PR. You're welcome to help us improve this library.

**Comment by Drizzlezhang** [comment]
@gejiaheng ok
