### ISSUE TITLE
这个地方写反了

### ISSUE THREAD

**Issue by cv0cv0** [zhihu/Matisse#200]
ProGuard
If you use Glide as your image engine, add rules as Glide's README says.
And add extra rule:
-dontwarn com.squareup.picasso.**
If you use Picasso as your image engine, add rules as Picasso's README says.
And add extra rule:
-dontwarn com.bumptech.glide.**

**Comment by jaycee88** [comment]
是的

**Comment by ylfzq** [comment]
The document is right, please make sure you know ProGuard

**Comment by adustdu2015** [comment]
![reverse](https://user-images.githubusercontent.com/17478136/30261634-2c561aec-9700-11e7-977f-3f6455c4a517.png)

**Comment by nekocode** [comment]
说写反的人，麻烦思考一下：
- 你认为写反的依据是什么？麻烦提供一下。
- 正如 @ylfzq 说的，你真的懂 Proguard 么？

**Comment by cv0cv0** [comment]
@nekocode 仔细看，Picasa和glide规则写反了，Picasa写的是glide的，glide写的是Picasa的。

**Comment by ylfzq** [comment]
@cv0cv0 就是这样才是对的

**Comment by angelkoh** [comment]
ProGuard
If you use Glide as your image engine, add rules as Glide's README says.
And add extra rule:
~~-dontwarn com.squareup.picasso.**~~ 
-dontwarn com.bumptech.glide.**

If you use Picasso as your image engine, add rules as Picasso's README says.
And add extra rule:
~~-dontwarn com.bumptech.glide.**~~
-dontwarn com.squareup.picasso.**
