### ISSUE TITLE
压根没有这个方法

### ISSUE THREAD

**Issue by adustdu2015** [zhihu/Matisse#201]
我引入了 compile 'com.zhihu.android:matisse:0.4.3'之后，
按按照Demo来说的话，
![qq 20170902155416](https://user-images.githubusercontent.com/17478136/29993966-9cd0eae6-8ff7-11e7-9729-dcffc34ee26f.png)

**Comment by adustdu2015** [comment]
方法根本没有，好吧。玩呢?

**Comment by nekocode** [comment]
开源并非义务，拜托注意下你的言辞好么。
另外，这个函数是在 `v0.5.0-alpha3` 加进去的，想用的话请依赖该版本或更新的版本。

**Comment by adustdu2015** [comment]
不好意思啦，大神，最起码sample要和README.md中要一致吧，对吧。

**Comment by nekocode** [comment]
@gejiaheng 非 release 的代码最好不要放到 master branch 上吧，不然还会有人提这种 issue。
