### ISSUE TITLE
您好，拍照后， 新图片没有更新列表图片没有变化

### ISSUE THREAD

**Issue by yangchaojiang** [zhihu/Matisse#202]
![image](https://user-images.githubusercontent.com/13806413/30021885-7bb40be0-919b-11e7-92d9-640bcd8b8707.png)
![image](https://user-images.githubusercontent.com/13806413/30021898-8bcf972e-919b-11e7-9370-93dcd493a5cc.png)
![image](https://user-images.githubusercontent.com/13806413/30021901-8fb21b96-919b-11e7-99d1-d778354683c9.png)

**Comment by magiclonw** [comment]
down下那个代码，在module里修改拍照完成后，sendBroadcast(new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE, Uri.fromFile(new File(path))));

**Comment by yangchaojiang** [comment]
好的。谢谢，作者不打算维护么
