### ISSUE TITLE
踩到个坑

### ISSUE THREAD

**Issue by BuLingzhuang** [zhihu/Matisse#203]
implementation 'com.github.bumptech.glide:glide:4.1.0' 不可用，会报以下错误：
java.lang.NoSuchMethodError: No virtual method load(Landroid/net/Uri;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager;
3.7.0的没问题

**Comment by xmjharry** [comment]
我也遇到这个问题了 请问楼主解决了吗

**Comment by BuLingzhuang** [comment]
解决不是写这了么，用3.7.0的glide（虽然gradle会报黄，强迫症就没办法了...Orz）

**Comment by xmjharry** [comment]
那我要弃坑了

**Comment by BuLingzhuang** [comment]
应该是4.1.0换了一些新方法吧，硬要用的话，你可以下载zhihu这个库的代码，module里面改成4.1.0，看哪些页面飘红，手动修改。最后项目依赖你改过的这个module

**Comment by xmjharry** [comment]
Matisse.imageEngine(new PicassoEngine()) 这样就OK

**Comment by lwj1994** [comment]
自己实现一下 ImageEngine 不就行了吗？我也是醉了。这么多 issues 真是质量堪忧。

**Comment by gejiaheng** [comment]
We will integrate Glide V4, see https://github.com/zhihu/Matisse/issues/167
