### ISSUE TITLE
这个库已经不能用了吧？

### ISSUE THREAD

**Issue by hugoFather** [zhihu/Matisse#211]
为啥这么多star...很多明显的bug都存在

**Comment by ylfzq** [comment]
难得是大厂出品的，而且是中国人的，主要是文档是中文的，所以用的人就多吧。。不过，这种项目一般都是KPI项目

**Comment by hugoFather** [comment]
@ylfzq 您好，kpi的意思就是这个项目只是练手的吗？

**Comment by ylfzq** [comment]
虽然不能一棍子把所有人都打死，但是大多数国内的开源项目都是因为要考核，必须要产出点什么。。不过这种事，讲明了就没意思了。。

P.S. 不管怎样，开源都是好事，我没有攻击任何人的意思，只是大环境如此

**Comment by hugoFather** [comment]
@ylfzq 您好，我在中型公司工作，还没有这样类似考核，我有点井底之蛙和局限，不过确实我也想自己开源一个框架，以便日后证明自己。在大公司都要考核这些课外拓展的吗？

**Comment by gejiaheng** [comment]
需要澄清几点：
- 项目的所有代码以及后期的维护，都是我一个人完成的。
- 知乎并没有形式上的以及实际的 KPI，我们使用的是 OKR。我个人在团队中没有任何产出方面的压力。
- 项目之前一段时间暂停维护，是因为个人原因。由于上面说的第一点，也确实没有人接手维护。
- 我后面会重新开始维护这个项目。
