### ISSUE TITLE
Use our custom theme

### ISSUE THREAD

**Issue by iad24** [zhihu/Matisse#217]
Hello. Im confused on how to use our custom theme. Your example is using the predefined of the library. How bout if the theme is from the Sample app?

**Comment by gejiaheng** [comment]
There are some predefined custom attrs [here](https://github.com/zhihu/Matisse/blob/master/matisse/src/main/res/values/attrs.xml). You can modify them as you wish. See https://github.com/zhihu/Matisse/wiki/Theme. You can reopen this issue if you have more questions.

**Comment by iad24** [comment]
Yes, I saw that page. Sorry but noob here. How do I use your attributes in my own theme in my styles.xml?

Ex. My custom theme is like this
`<style name="MyOwnTheme" parent="Theme.AppCompat.NoActionBar">
    <item name="album.dropdown.title.color">@color/colorAccent</item>
</style>`

Then it will throw compile error like this:
![screen shot 2017-09-22 at 11 16 16 am](https://user-images.githubusercontent.com/15226261/30728047-f5b2928c-9f87-11e7-9106-7037ee8a91f6.png)

The Sample app only used the theme defined in the lib. How about the Sample making its own theme?

**Comment by iad24** [comment]
@gejiaheng any updates on this one? It is not yet resolved in my side.

**Comment by yuanjunli** [comment]
@iad24  i meet the same problem. but when i remove the  <item name="album.dropdown.title.color">@color/colorAccent</item> and build success. the i add the remove item and i work

**Comment by yuanjunli** [comment]
@iad24  i meet the same problem. but when i remove the  `<item name="album.dropdown.title.color">@color/colorAccent</item>` and build success. the i add the remove item and i work
