### ISSUE TITLE
图片预览问题

### ISSUE THREAD

**Issue by xia-weiyang** [zhihu/Matisse#226]
预览手机拍照的图片时，加载不出来，黑屏。
而，预览其它图片，如屏幕截图等时，可以正常显示。

**Comment by wpq2014** [comment]
首先非常感谢知乎开源这个库！
有的图确实预览不了，一片黑，我测过了，知乎的App也是，希望知乎尽快解决下吧

**Comment by 16fangougou** [comment]
https://github.com/zhihu/Matisse/issues/227

**Comment by lcl6** [comment]
图片分辨率超过8192就无法预览

**Comment by REBOOTERS** [comment]
@lcl6 try with latest version
