### ISSUE TITLE
【超大图无法显示】Bitmap too large to be uploaded into a texture (1200x6298, max=4096x4096)

### ISSUE THREAD

**Issue by SherlockGougou** [zhihu/Matisse#227]
对于尺寸超过GPU的openglRender的限制时【大部分都是4096】，无法显示，并且OOM

![image](https://user-images.githubusercontent.com/17920617/31540046-1c6fad58-afd0-11e7-957f-17acf69411a7.png)

**Comment by 16fangougou** [comment]
我自己clone下来修复了一下，解决了问题：[https://github.com/16fangougou/Matisse.git](url)
