### ISSUE TITLE
有没有针对多张图片或1个视频的方法

### ISSUE THREAD

**Issue by jacknonebug** [zhihu/Matisse#230]

**Comment by iad24** [comment]
can edit the the text to english? this is for all developers that want to see if its the issue they are facing too

**Comment by cjhandroid** [comment]
自己重新写吧，我就是自己写的

![image](https://user-images.githubusercontent.com/11549035/34663671-d655b22e-f492-11e7-91ac-37a61d045164.png)

**Comment by jacknonebug** [comment]
嗯 只能重写了
