### ISSUE TITLE
首页readMe 没有更新？？？

### ISSUE THREAD

**Issue by lvwanyou** [zhihu/Matisse#254]

**Comment by lvwanyou** [comment]
你说明的版本是0.4.3，但是你demo的版本我也不知道是多少。你的源码demo中的Matisse.obtainPathResult(data)方法在除了在你demo中可以用，在其他地方用不了。

**Comment by Lollipopll** [comment]
demo是测试版的，你说的那是新加的应该，readme中是稳定版的

**Comment by xuekaiqi** [comment]
0.4.3 这个版本Matisse.obtainPathResult(data) 这个方法呢？怎么回事
