### ISSUE TITLE
等了半年依然未发布可用版本，这个项目作为知乎官方开源项目真是丢人

### ISSUE THREAD

**Issue by liunewshine** [zhihu/Matisse#278]
拍照各种bug，想着先用着，毕竟是大公司的开源项目，质量肯定有保证，等等肯定修复。
结果半年过去了，根本没有改进，连个私人项目都不如。

我知道开源项目作者没有义务做什么，爱用不用，请换个理由喷我

**Comment by gejiaheng** [comment]
@liunewshine 很抱歉这一点给你造成困扰，这个项目初始的拍照功能，是为了扩展性加入的，没有做任何兼容性测试，后续也没有投入做这方面的开发，这个是我个人的过失。更妥当的做法我觉得应该是：
- 说明这个功能的可用性
- 投入精力做好这个功能 

可惜我两者都没做好吧。

**Comment by directionyu** [comment]
@liunewshine  拍照有bug 你可以fork 优化完提交，这样也为大家出一份力，不要总拿现成的
