### ISSUE TITLE
使用v0.5.0-beta3，编译出现Error:No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

### ISSUE THREAD

**Issue by LiuLinXin** [zhihu/Matisse#280]
今天早上来编译项目，出现Error:(15, 21) No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.等错误。经过一个一个排查最后发现是compile 'com.zhihu.android:matisse:+'动态引用了2017-12-13更新了v0.5.0-beta3（之前用的是v0.5.0-beta2）。而v0.5.0-beta3中build ext.supportLibVersion = '26.1.0'。

把compile 'com.zhihu.android:matisse:+'替换成compile 'com.zhihu.android:matisse:0.5.0-beta2'后问题解决

**Comment by hdd2015** [comment]
谢谢
