### ISSUE TITLE
MatisseActivity  点击进去MatisseActivity闪退  说是TextView绘制错误 

### ISSUE THREAD

**Issue by sxwn** [zhihu/Matisse#284]
楼主，我是把库里的东西都写成了一个包，全放在包下面了，但是跳转到MatisseActivity的时候就报错了，错误信息我截个张图，没查出来，请看下
![error](https://user-images.githubusercontent.com/9957430/34067895-d6ecbeae-e26c-11e7-8825-7a7f0030ec6e.png)

**Comment by yuanjunli** [comment]
我遇到同样的问题，是自定义style 错了，使用默认两种样式或者按照wiki的描述自定义theme能解决。

**Comment by sxwn** [comment]
谢谢，我添加依赖暂时解决了。
在2017年12月18日 14:57，NEXTB<notifications@github.com> 写道：

我遇到同样的问题，是自定义style 错了，使用默认两种样式或者按照wiki的描述自定义theme能解决。

**Comment by xia-weiyang** [comment]
我也遇到这个问题了，使用的是0.5.0-beta3版本，出现的概率比较低，该怎么解决呢。
这是我自定义的style
 <style name="Matisse.Custom" parent="Matisse.Zhihu">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="page.bg">@color/colorWhite</item>
        <item name="bottomToolbar.bg">@color/colorWhite</item>
    </style>

**Comment by ethanhua** [comment]
@sxwn 你添加了什么依赖解决的？ 我并没有自定义style样式，使用的是Matisse的默认样式也报这个错
