### ISSUE TITLE
不走onActivityResult方法

### ISSUE THREAD

**Issue by to686312** [zhihu/Matisse#296]
Matisse.from(mActivity)
                        .choose(MimeType.of(MimeType.JPEG, MimeType.PNG))
                        .theme(R.style.Matisse_Dracula)
                        .restrictOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT)
                        .captureStrategy(new CaptureStrategy(true,GetPath()))
                        .capture(true)
                        .thumbnailScale(0.85f)
                        .countable(false)
                        .maxSelectable(1)
                        .imageEngine(new GlideEngineOwn())
                        .forResult(106);

这样调了   在fragment中 他不走onActivityResult方法

**Comment by SnowyTomorrow** [comment]
如果你是在Fragment里调用的话，Matisse.from()这个入参传当前Fragment，不要传容器activity，回调还是走onActivityResult方法
