### ISSUE TITLE
Is image compress feature in todo list?

### ISSUE THREAD

**Issue by zhangchaoxu** [zhihu/Matisse#3]

**Comment by parcool** [comment]
anyway，is's a very nice lib for design!

**Comment by gejiaheng** [comment]
@zhangchaoxu 
Thanks for bring it up. We still have much to do with media selecting feature (yeah, media, not just images). The priority would be the following two things currently:
- Make the code clean and robust
- Support video selecting

And I want to keep this library simple. So image compression is not on the todo list now. If we decide to support it in the future, I may say it's better to include it as a plugin or extension.

**Comment by gejiaheng** [comment]
@istudy2012 
I don't quite understand what you mean. The result is just a collection of Uris pointing to the selected images. It's your choice what to do with those images.

**Comment by CoXier** [comment]
@gejiaheng 
I guess @istudy2012 means it's better for providing UI interface to guide user choose original image or not.

Just a interface.As for how to compress image is on user's duty and this lib only returns the Uri of the image.

**Comment by gejiaheng** [comment]
@CoXier 
Thanks, I got it.
