### ISSUE TITLE
能否暴露图片预览的接口出来？

### ISSUE THREAD

**Issue by Limitlesser** [zhihu/Matisse#302]
比如现在我现在已经有一组图片id，想在matisse中预览让用户选择发送

**Comment by REBOOTERS** [comment]
这个没什么意义吧

**Comment by jamin918** [comment]
暴露预览接口后，发送出去的图片或者接收到的图片能使用这个库进行预览。

**Comment by guoleifei** [comment]
同求。
最好可以传入一组数据进行预览。否则还要单独实现一个预览其他图片的功能。
