### ISSUE TITLE
小米手机点击拍照闪退，能不能不要拍照那个，仅仅选择照片就好

### ISSUE THREAD

**Issue by sxwn** [zhihu/Matisse#309]
小米手机点击拍照闪退，能不能不要拍照那个，仅仅选择照片就好，预测可能别的型号手机也是闪退，

**Comment by walkthehorizon** [comment]
兄弟能下个Demo自己泡一泡测测调试调试再来issue么

**Comment by sxwn** [comment]
好的，已经调试可以了，下下来跑不到studio3.0 上，所以就发了个issue，不好意思，谢谢~~~




发自网易邮箱大师
在2018年1月4日 19:44，Horizon<notifications@github.com> 写道：

兄弟能下个Demo自己泡一泡测测调试调试再来issue么
