### ISSUE TITLE
很多机型拍照都有问题，比如魅族，小米

### ISSUE THREAD

**Issue by walkthehorizon** [zhihu/Matisse#311]
很多机型未适配，亲测魅族Pro6拍照后点击完成无响应，版本6.0，部分小米机也是，Matisse 版本0.5.0-beta3

**Comment by HuanTanSheng** [comment]
我也遇到了这个问题，因此我写了一个[EasyPhotos](https://github.com/HuanTanSheng/EasyPhotos) （实在是不得不自己写一套，否则魅族的上线测试都过不了），它解决了魅族等产品的兼容问题，至今产品也没有报过bug，是稳定的。
最后希望matisse越来越完善，如果可以，谁都不想自己造轮子。期待以后matisse成为最棒的图片选择框架。

**Comment by HuanTanSheng** [comment]
@walkthehorizon 
我也遇到了这个问题，因此我写了一个[EasyPhotos](https://github.com/HuanTanSheng/EasyPhotos) （实在是不得不自己写一套，否则魅族的上线测试都过不了），它解决了魅族等产品的兼容问题，至今产品也没有报过bug，是稳定的。
最后希望matisse越来越完善，如果可以，谁都不想自己造轮子。期待以后matisse成为最棒的图片选择框架。

**Comment by walkthehorizon** [comment]
魅族无法开启的情况在上次出现后截止到现在并未复现，所以关闭该issue
