### ISSUE TITLE
我无耻地在这里推广我的同类框架EasyPhotos的原因。

### ISSUE THREAD

**Issue by HuanTanSheng** [zhihu/Matisse#312]
相机和图片选择曾是我的一个开发痛点（问题集中在颜值和兼容上），所以知乎发布Matisse后我特别感动，有一种找到家的感觉。

我相信，知乎开发的matisse，绝对不会在兼容上（尤其是国内rom兼容上）出现问题。
于是我把它推荐给我所有身边android同仁。

我的新产品也使用了该框架，并且我们公司的老产品的开发同事也被我说动，更换了相册选择框架。

然后，我收到了小米、魅族的应用申请不通过的通知。

当然，还有其他平台上线后的各种bug日志。

然后我看了matisse的Issues。我开始跟被我说动改换相册框架的同仁们道歉。因为所有的问题其实在Issues里面都有，而且一直没有得到解决，我在本可以了解这些情况的前提下，没有了解，而直接跟同仁们推荐了matisse，造成了损失。

我痛定思痛，自己开发了[EasyPhotos](https://github.com/HuanTanSheng/EasyPhotos)，借鉴了matisse和其他同类框架，最后柔和了一个最起码在兼容上是没有问题的框架。美观不美观，大家可以用自己的审美看一下。

它可以实现如下功能：
android拍照、相册选择、文字贴纸、自定义相册UI、相册界面填充广告、拼图、图片添加水印、图片宽高和文件大小限制、把View画成Bitmap、图片预览、图片缩放、媒体文件更新到媒体库、保存Bitmap到指定文件夹、图片单选、图片多选等功能，而无需考虑运行时权限、无图片显示、工具库与应用UI不统一等问题

如果可以，谁都不想自己造轮子，重复造已有的轮子。
所以，我希望matisse能够越来越完善，知乎的大神们可以多一点时间来完善matisse。
感谢。

知乎的大神们：
你们好！
我没有在任何地方发过类似言论，只在这里发了。因为在别的地方发，我感觉味道就变了，也不是我的初心。我希望matisse完善，然后我就不需要在做EasyPhotos的维护工作，甚至自己都不用，而是用matisse，我认为用的人越多的框架越稳定，越高级。而这种东西，有一个就够了 。

**Comment by HuanTanSheng** [comment]
补充一下，我是在17年七八月份的时候使用matisse的。

**Comment by junyuecao** [comment]
不错不错。不过，Issue不是广告墙

**Comment by a1265137718** [comment]
Matisse 已死

**Comment by Siomt** [comment]
入了Matisse  的坑
