### ISSUE TITLE
[OS 7.0] Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/file from pid=12793, uid=10196 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()

### ISSUE THREAD

**Issue by khalid-mahmood** [zhihu/Matisse#317]
Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/file from pid=12793, uid=10196 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
getting this error on MI Note4 7.0 OS

**Comment by junyuecao** [comment]
Did you request for permission before trying to select pics?

**Comment by khalid-mahmood** [comment]
@junyuecao 
not requested.
i think this permission should handle in library for Android.M and above

**Comment by junyuecao** [comment]
> So if you are targeting Android 6.0+, you need to handle runtime permission request before next step.

See https://github.com/zhihu/Matisse/blob/master/README.md#how-do-i-use-matisse

**Comment by mymbrooks** [comment]
@junyuecao 
On Android 7.0 + you need to request uri permission like this

            Intent intent = new Intent(Intent.ACTION_VIEW);
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
                File file = new File(Environment.getExternalStorageDirectory().getPath() + "/Astrill.apk");
                Uri uri = FileProvider.getUriForFile(this, "io.ruibu.fileprovider", file);
                intent.setDataAndType(uri, "application/vnd.android.package-archive");
            } else {
                intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                File file = new File(Environment.getExternalStorageDirectory().getPath() + "/Astrill.apk");
                Uri uri = Uri.fromFile(file);
                intent.setDataAndType(uri, "application/vnd.android.package-archive");
            }
            startActivity(intent);

In AndroidManifest.xml:
        <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="io.ruibu.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/filepaths" />
        </provider>

@xml/filepaths"
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path
        name="allfiles"
        path="" />
</paths>

**Comment by mymbrooks** [comment]
@khalid-mahmood 

On Android 7.0 + sample:
        Intent intent = new Intent(Intent.ACTION_VIEW);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
            File file = new File(Environment.getExternalStorageDirectory().getPath() + "/Astrill.apk");
            Uri uri = FileProvider.getUriForFile(this, "io.ruibu.fileprovider", file);
            intent.setDataAndType(uri, "application/vnd.android.package-archive");
        } else {
            intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            File file = new File(Environment.getExternalStorageDirectory().getPath() + "/Astrill.apk");
            Uri uri = Uri.fromFile(file);
            intent.setDataAndType(uri, "application/vnd.android.package-archive");
        }
        startActivity(intent);

AndroidManifest.xml
 <application
        android:name="io.ruibu.system.SystemApplication"
        android:allowBackup="true"
        android:hardwareAccelerated="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="io.ruibu.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/filepaths" />
        </provider>
......


@xml/filepaths
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path
        name="allfiles"
        path="" />
</paths>

**Comment by REBOOTERS** [comment]
this library will not handle Android Permissions case.
