### ISSUE TITLE
无法使用拍照功能

### ISSUE THREAD

**Issue by nixiashiguang** [zhihu/Matisse#322]
MediaStoreCompat类中，生成保存的文件路径变成了：Failed to find configured root that contains /storage/emulated/0/PicturesJPEG_20180125_135321_.jpg

` private File createImageFile() throws IOException {

        // Create an image file name

        String timeStamp = new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date());

        String imageFileName = "JPEG_" + timeStamp + "_";

        File storageDir;

        if (mCaptureStrategy.isPublic) {

            storageDir = Environment.getExternalStoragePublicDirectory(

                    Environment.DIRECTORY_PICTURES);

        } else {

            storageDir = mContext.get().getExternalFilesDir(Environment.DIRECTORY_PICTURES);

        }

        return new File(storageDir + imageFileName + ".jpg");

    }`

**Comment by nixiashiguang** [comment]
使用说明该更新了

**Comment by zqbemail** [comment]
你怎么解决的？
