### ISSUE TITLE
能否加入类似retorfit的adapter机制，让用户自己选择图片加载框架

### ISSUE THREAD

**Issue by a1018875550** [zhihu/Matisse#33]
项目默认引入两个图片加载框架是否太多余，能否弄个类似retorfit的adapter机制，让用户自己选择图片加载框架

**Comment by gejiaheng** [comment]
@a1018875550 
Thanks for your suggestion. But Matisse behaves just like you said. The two dependencies of Glide and Picasso use `provided` scope. You can only add compile dependency of the image engine your choose in your application's gradle file.
