### ISSUE TITLE
An image res' name may be wrong

### ISSUE THREAD

**Issue by TonnyL** [zhihu/Matisse#332]
All the empty placeholder images are named **ic_empty_zhihu.png**, but in [drawable-xhdpi](https://github.com/zhihu/Matisse/tree/master/matisse/src/main/res/drawable-xhdpi), there is no such file, but a image named **[ic_emtpy_light.png](https://github.com/zhihu/Matisse/blob/master/matisse/src/main/res/drawable-xhdpi/ic_emtpy_light.png)** was found. I think it may be a bug🐛.

Here are the screenshots.
<img width="596" alt="ic_emtpy_light.png in folder drawable-xhdpi" src="https://user-images.githubusercontent.com/13329148/35898932-788eb04e-0c04-11e8-8d16-bb92c37dbb75.png">
<img width="532" alt="ic_empty_zhihu.png in folder drawable-mdpi" src="https://user-images.githubusercontent.com/13329148/35898933-78d69af8-0c04-11e8-8b27-288edceb609b.png">
<img width="590" alt="ic_empty_zhihu.png in folder drawable-hdpi" src="https://user-images.githubusercontent.com/13329148/35898934-791fb81e-0c04-11e8-9fb9-4c135f262c0d.png">

**Comment by REBOOTERS** [comment]
en ,it's really is a bug .will be fixed in next release.

**Comment by TonnyL** [comment]
@REBOOTERS 

Thanks for your amazing work!
