### ISSUE TITLE
添加依赖后，报找不到包的错误

### ISSUE THREAD

**Issue by Recycl** [zhihu/Matisse#341]
都是按照文档添加的依赖，不知道到为什么。报这个错误 

FATAL EXCEPTION: main
                                                                    Process: com.huaxin.hxcloud, PID: 11616
                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/zhihu/matisse/Matisse;

**Comment by 164738777** [comment]
大兄弟，混淆规则加了么？
