### ISSUE TITLE
crushException

### ISSUE THREAD

**Issue by Ashion-AS** [zhihu/Matisse#35]
05-04 11:53:07.868  4608 29537 E Parcel  : Class not found when unmarshalling: com.zhihu.matisse.internal.entity.Item
05-04 11:53:07.868  4608 29537 E Parcel  : java.lang.ClassNotFoundException: com.zhihu.matisse.internal.entity.Item
05-04 11:53:07.868  4608 29537 E Parcel  :      at java.lang.Class.classForName(Native Method)
05-04 11:53:07.868  4608 29537 E Parcel  :      at java.lang.Class.forName(Class.java:400)
05-04 11:53:07.868  4608 29537 E Parcel  :      at android.os.Parcel.readParcelableCreator(Parcel.java:2517)
05-04 11:53:07.868  4608 29537 E Parcel  :      at android.os.Parcel.readParcelable(Parcel.java:2471)
05-04 11:53:07.868  4608 29537 E Parcel  :      at android.os.Parcel.readValue(Parcel.java:2374)
05-04 11:53:07.868  4608 29537 E Parcel  :      at android.os.Parcel.readArrayMapInternal(Parcel.java:2727)
05-04 11:53:07.868  4608 29537 E Parcel  :      at android.os.BaseBundle.unparcel(BaseBundle.java:269)
05-04 11:53:07.868  4608 29537 E Parcel  :      at android.os.BaseBundle.getString(BaseBundle.java:992)
05-04 11:53:07.868  4608 29537 E Parcel  :      at android.content.Intent.getStringExtra(Intent.java:6702)
05-04 11:53:07.868  4608 29537 E Parcel  :      at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:336)
05-04 11:53:07.868  4608 29537 E Parcel  :      at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1097)
05-04 11:53:07.868  4608 29537 E Parcel  :      at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5767)
05-04 11:53:07.868  4608 29537 E Parcel  :      at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5572)
05-04 11:53:07.868  4608 29537 E Parcel  :      at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:176)
05-04 11:53:07.868  4608 29537 E Parcel  :      at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3573)
05-04 11:53:07.868  4608 29537 E Parcel  :      at android.os.Binder.execTransact(Binder.java:573)
05-04 11:53:07.868  4608 29537 E Parcel  : Caused by: java.lang.ClassNotFoundException: com.zhihu.matisse.internal.entity.Item
05-04 11:53:07.868  4608 29537 E Parcel  :      at java.lang.Class.classForName(Native Method)
05-04 11:53:07.868  4608 29537 E Parcel  :      at java.lang.BootClassLoader.findClass(ClassLoader.java:1346)
05-04 11:53:07.868  4608 29537 E Parcel  :      at java.lang.BootClassLoader.loadClass(ClassLoader.java:1406)
05-04 11:53:07.868  4608 29537 E Parcel  :      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05-04 11:53:07.868  4608 29537 E Parcel  :      ... 16 more
05-04 11:53:07.868  4608 29537 E Parcel  : Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by gejiaheng** [comment]
@Ashion-AS 
Thanks for reporting this crash. Would you please provide more details about this bug and the reproduce procedures if possible.

**Comment by Ashion-AS** [comment]
这个问题产生的步骤是，点击zhihu按钮，然后进去选择图片，取消，选择，预览，再返回。后面我又重试了很多次没有再复现，感觉这个问题是小概率事件。

**Comment by gejiaheng** [comment]
@Ashion-AS 
Are you using Zhihu App or Matisse sample App when this crash occurs?

**Comment by Ashion-AS** [comment]
Matisse sample App，点击Zhihu 按钮，进入那个页面操作后，崩溃的。

**Comment by unixzii** [comment]
Seems like the resuming activity in sample app is recycled, and when system recreates the activity, it cannot get the right class loader to unmarshal the `com.zhihu.matisse.internal.entity.Item` class which implemented `Parcelable`. Maybe `Intent#setExtrasClassLoader` can help.
