### ISSUE TITLE
java.lang.NoClassDefFoundError: android.support.v4.animation.AnimatorCompatHelper

### ISSUE THREAD

**Issue by megicfish** [zhihu/Matisse#360]
按照官方方法启动MatisseActivity.class时报出
java.lang.NoClassDefFoundError: android.support.v4.animation.AnimatorCompatHelper错误，程序崩溃，
系统版本4.3 手机型号 三星gt-n7108
ps：建议用户自定义imageloader，而不是在项目中使用了指定的Glide版本

**Comment by REBOOTERS** [comment]
NoClassDefFoundError 的原因应是 support v4 库的版本不一致导致。
