### ISSUE TITLE
大佬什么时候升级Glide4.x的啊

### ISSUE THREAD

**Issue by qianshengta** [zhihu/Matisse#361]
大佬什么时候升级Glide4.x的啊  我新项目用的Glide4.6.1  用不了啊。
有大佬吧自定义的代码发一下吗？(原谅我这可耻的伸手党)

**Comment by aaironman** [comment]
public class Glide4Engine implements ImageEngine {

	@Override
	public void loadThumbnail(Context context, int resize, Drawable placeholder, ImageView imageView, Uri uri) {
		GlideApp.with(context)
				.asBitmap()  // some .jpeg files are actually gif
				.load(uri)
				.placeholder(placeholder)
				.override(resize, resize)
				.centerCrop()
				.into(imageView);
	}

	@Override
	public void loadGifThumbnail(Context context, int resize, Drawable placeholder, ImageView imageView,
								 Uri uri) {
		GlideApp.with(context)
				.asBitmap()
				.load(uri)
				.placeholder(placeholder)
				.override(resize, resize)
				.centerCrop()
				.into(imageView);
	}

	@Override
	public void loadImage(Context context, int resizeX, int resizeY, ImageView imageView, Uri uri) {
		GlideApp.with(context)
				.load(uri)
				.override(resizeX, resizeY)
				.priority(Priority.HIGH)
				.into(imageView);
	}

	@Override
	public void loadGifImage(Context context, int resizeX, int resizeY, ImageView imageView, Uri uri) {
		GlideApp.with(context)
				.asGif()
				.load(uri)
				.override(resizeX, resizeY)
				.priority(Priority.HIGH)
				.into(imageView);
	}

	@Override
	public boolean supportAnimatedGif() {
		return true;
	}
}
