### ISSUE TITLE
图库里没有包括Picture文件也就是拍照保存的地方

### ISSUE THREAD

**Issue by qianshengta** [zhihu/Matisse#362]
图库里没有包括Picture文件也就是拍照保存的地方。我拍照保存在Picture文件下 但是图库里没有包括这个文件夹 也就是说我以前拍照得到的图片就不能用了

**Comment by JasonZhu19910601** [comment]
是的，希望作者大佬可以完善一下，个人很喜欢matisse

**Comment by xiaonanhailili** [comment]
图库中得pictures文件夹是存在的,但是你必须使用系统自带的图库去进行刷新才能在matisse中显示(难道是因为查询延时?)

**Comment by REBOOTERS** [comment]
`                                            .captureStrategy(
                                                    new CaptureStrategy(true, "com.zhihu.matisse.sample.fileprovider"))`

如上，CaptureStrategy 第一个参数

- 如果为 true，拍照后图片将保存在  /storage/emulated/0/Pictures/ 文件夹下

- 如果为 false ,图片将保存在 /storage/emulated/0/Android/data/{packagename}/cache/Pictures/ 文件夹下

对于第二种情况，因为是应用私有目录，将不会被扫描到。
