### ISSUE TITLE
glide都4.7.1了呀！matisse才支持到3.7.0

### ISSUE THREAD

**Issue by bluefish625** [zhihu/Matisse#366]
glide都4.7.1了呀！matisse才支持到3.7.0！
可以更新一下了，一个大版本号了。

**Comment by sdwfqin** [comment]
尝试一下自定义ImageEngine，继承matisse的ImageEngine并实现对应方法就可以
我这边这样搞可以用4.x的glide

```
public class MatisseGlideEngine implements ImageEngine {
}
```

**Comment by REBOOTERS** [comment]
Matisse 内部无法同时实现 Glide V4 和 V3 的 GlideEngine 。所以为了兼容使用 Glide 3.7.0 的项目，Matisse 内部依旧只有针对与Glide V3 的GlideEngine 。如果项目使用到了 Glide V4 ，需要自己实现一下GlideEngine 。具体可以参考项目sample 。

**Comment by dongorigin** [comment]
将Engine的实现单独抽取出来，单独发布，可以从根本上解决问题，这样Matisse内部不需要依赖Glide的某个版本
