### ISSUE TITLE
如何设置不显示gif图片？

### ISSUE THREAD

**Issue by only0315** [zhihu/Matisse#371]
我使用Demo提供的filter，并没有过滤掉gif图片呀？有好的解决方式吗

**Comment by only0315** [comment]
在CursorLoader的selection参数附加" AND " + MediaStore.MediaColumns.MIME_TYPE + "!='image/gif'"

**Comment by thinkfeed** [comment]
Set<MimeType> mimeTypes = new HashSet<>();
mimeTypes.addAll(EnumSet.of(MimeType.JPEG, MimeType.PNG, MimeType.BMP, MimeType.WEBP));
mimeTypes.addAll(MimeType.ofVideo());
Matisse.from(this).choose(mimeTypes,false)

maybe you can try this code to filter the git
