### ISSUE TITLE
Set max selectable image/video at the same time

### ISSUE THREAD

**Issue by truyenz** [zhihu/Matisse#402]
How I can set max selectable for each type and max selectable for all of them?
For example:
- For image type, i want to set max selectable are 5 
- For video type, i want to set max selectable is 1 
And max selectable all of them are 5
Sorry about my english! :)) Thanks!

**Comment by REBOOTERS** [comment]
you can try with 

`
maxSelectablePerMediaType(int maxImageSelectable, int maxVideoSelectable)
`
