### ISSUE TITLE
！！！很多机型出现闪退，具体查看log

### ISSUE THREAD

**Issue by 57951862** [zhihu/Matisse#405]
com.zhihu.matisse.internal.entity.Item.boolean isGif()(Item.java:91)
--
2 com.zhihu.matisse.internal.ui.widget.PhotoGrid.void setGifTag()(PhotoGrid.java:88)
3 com.zhihu.matisse.internal.ui.widget.PhotoGrid.void bindPhoto(com.zhihu.matisse.internal.entity.Item)(PhotoGrid.java:78)
4 com.zhihu.matisse.internal.ui.adapter.AlbumPhotosAdapter.void onBindViewHolder(android.support.v7.widget.RecyclerView$ViewHolder,android.database.Cursor)(AlbumPhotosAdapter.java:111)
5 com.zhihu.matisse.internal.ui.adapter.RecyclerViewCursorAdapter.void onBindViewHolder(android.support.v7.widget.RecyclerView$ViewHolder,android.database.Cursor)(RecyclerViewCursorAdapter.java:44)
6 ##_parent_##2##_parent_##
7 ##_child_## void onBindViewHolder(android.support.v7.widget.RecyclerView$ViewHolder,int)##_child_##
8 ##_child_## int getItemViewType(int,android.database.Cursor)##_child_##
9 android.support.v7.widget.RecyclerView$a.a(RecyclerView.java:6673)
10 android.support.v7.widget.RecyclerView$a.b(RecyclerView.java:6714)
11 android.support.v7.widget.RecyclerView$n.a(RecyclerView.java:5647)
12 android.support.v7.widget.RecyclerView$n.a(RecyclerView.java:5913)
13 android.support.v7.widget.RecyclerView$n.a(RecyclerView.java:5752)
14 android.support.v7.widget.RecyclerView$n.c(RecyclerView.java:5748)

**Comment by Novice9527** [comment]
解决了吗？有什么好的方法

**Comment by imgod1** [comment]
同
0.	java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
1.	com.zhihu.matisse.internal.entity.Item.isGif(Item.java:91)
2.	com.zhihu.matisse.internal.ui.widget.PhotoGrid.setGifTag(PhotoGrid.java:88)
3.	com.zhihu.matisse.internal.ui.widget.PhotoGrid.bindPhoto(PhotoGrid.java:78)
4.	com.zhihu.matisse.internal.ui.adapter.AlbumPhotosAdapter.onBindViewHolder(AlbumPhotosAdapter.java:111)
5.	com.zhihu.matisse.internal.ui.adapter.RecyclerViewCursorAdapter.onBindViewHolder(RecyclerViewCursorAdapter.java:44)
6.	android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
7.	android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
8.	android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
9.	android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
10.	android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
11.	android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
12.	android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
13.	android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
14.	android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
15.	android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
16.	android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
17.	android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
18.	android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
19.	android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
20.	android.view.View.layout(View.java:19781)
21.	android.view.ViewGroup.layout(ViewGroup.java:6144)
22.	android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
23.	android.widget.FrameLayout.onLayout(FrameLayout.java:261)
24.	android.view.View.layout(View.java:19781)
25.	android.view.ViewGroup.layout(ViewGroup.java:6144)
26.	android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
27.	android.widget.FrameLayout.onLayout(FrameLayout.java:261)
28.	android.view.View.layout(View.java:19781)
29.	android.view.ViewGroup.layout(ViewGroup.java:6144)
30.	android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
31.	android.view.View.layout(View.java:19781)
32.	android.view.ViewGroup.layout(ViewGroup.java:6144)
33.	android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
34.	android.widget.FrameLayout.onLayout(FrameLayout.java:261)
35.	android.view.View.layout(View.java:19781)
36.	android.view.ViewGroup.layout(ViewGroup.java:6144)
37.	android.widget.LinearLayout.setChildFrame(LinearLayout.java:1816)
38.	android.widget.LinearLayout.layoutVertical(LinearLayout.java:1660)
39.	android.widget.LinearLayout.onLayout(LinearLayout.java:1569)
40.	android.view.View.layout(View.java:19781)

**Comment by REBOOTERS** [comment]
什么版本？

**Comment by REBOOTERS** [comment]
same with #422  @57951862 @imgod1

**Comment by imgod1** [comment]
抱歉 这两天有点忙 没有及时回复
 compile 'com.zhihu.android:matisse:0.4.3'
稳定版
