### ISSUE TITLE
能否提供一个直接开启相机拍照的api？产品经理说要点两次才能拍照，必须改

### ISSUE THREAD

**Issue by 18872731525** [zhihu/Matisse#406]
能否提供一个直接开启相机拍照的api？
产品经理说要点两次才能拍照，必须改

**Comment by leeyun** [comment]
直接调用系统相机就好了然后自己裁剪。
`private Uri photoURI;

  private void dispatchTakePictureIntent(int requestCode) {
    Intent takePictureIntent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
    // Ensure that there's a camera activity to handle the intent
    if (takePictureIntent.resolveActivity(getPackageManager()) != null) {
      // Create the File where the photo should go
      File photoFile = null;
      try {
        photoFile = createImageFile();
      } catch (IOException ex) {
        // Error occurred while creating the File
      }
      // Continue only if the File was successfully created
      if (photoFile != null) {
        photoURI = FileProvider.getUriForFile(this, BuildConfig.APPLICATION_ID + ".file.provider",
            photoFile);
        takePictureIntent.putExtra(MediaStore.EXTRA_OUTPUT, photoURI);
        startActivityForResult(takePictureIntent, requestCode);
      }
    }
  }

  String mCurrentPhotoPath;

  private File createImageFile() throws IOException {
    final String cameraOutDir = BoxingFileHelper.getExternalDCIM(null);
    //// Create an image file name
    String timeStamp = new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date());
    String imageFileName = "JPEG_" + timeStamp + "_";
    File storageDir = new File(cameraOutDir);
    File image = File.createTempFile(imageFileName,  /* prefix */
        ".jpg",         /* suffix */
        storageDir      /* directory */);
    // Save a file: path for use with ACTION_VIEW intents
    mCurrentPhotoPath = image.getAbsolutePath();
    return image;
  }`

像这样，注意7.0权限的配置还有不要去取Intent的回调数据自己保存图片地址进行图片处理，因为部分机型是不返回图片数据的。

**Comment by REBOOTERS** [comment]
@leeyun right !
