### ISSUE TITLE
The summary of bugs from version 0.4.3

### ISSUE THREAD

**Issue by yandeqing** [zhihu/Matisse#407]
问题一 （gif判断相关闪退）
java.lang.NullPointerException
Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
com.zhihu.matisse.internal.entity.Item.boolean isGif()(Item.java:91)

问题二 （布局问题闪退）
 java.lang.UnsupportedOperationException
 Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f010004 a=-1}
 com.zhihu.matisse.ui.MatisseActivity.void onCreate(android.os.Bundle)(MatisseActivity.java:83)

**Comment by REBOOTERS** [comment]
感谢你的反馈，最新版本 0.5.1 已解决你提到的两个问题。

**Comment by yandeqing** [comment]
收到，谢谢!

2018-07-05 

546218945 



发件人：Rookie <notifications@github.com>
发送时间：2018-07-05 13:46
主题：Re: [zhihu/Matisse] The summary of bugs from version 0.4.3 (#407)
收件人："zhihu/Matisse"<Matisse@noreply.github.com>
抄送："yandeqing"<yan546218945@qq.com>,"Author"<author@noreply.github.com>

Closed #407.
