### ISSUE TITLE
原图选择和非原图选择有什么区别

### ISSUE THREAD

**Issue by XinleiChenJohn** [zhihu/Matisse#414]
我开启了原图选择，分别选择了两次一张图片，一张非原图一张是原图，选择后发现大小是一样的，压缩是框架在做，还是使用者自己做？方便指导一下么？

**Comment by REBOOTERS** [comment]
这个是为了方便 开发者 获取用户是否有使用原图的意愿。
在onActivityResult中可以通过Matisse.obtainOriginalState(Intent data)  方法获取用户是否选择了使用原图，根据这个boolean 值，由开发者决定是否在后续业务中对图片进行压缩处理。
