### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/zhihu/matisse/R$plurals

### ISSUE THREAD

**Issue by xionglihui** [zhihu/Matisse#421]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/zhihu/matisse/R$plurals

**Comment by zacharyyy** [comment]
```
Warning: com.zhihu.matisse.internal.model.SelectedItemCollection: can't find referenced class com.zhihu.matisse.R$plurals
Warning: com.zhihu.matisse.internal.model.SelectedItemCollection: can't find referenced class com.zhihu.matisse.R$plurals
Warning: com.zhihu.matisse.internal.ui.BasePreviewActivity: can't find referenced field 'int error_over_original_size' in program class com.zhihu.matisse.R$string
Warning: com.zhihu.matisse.internal.ui.BasePreviewActivity$2: can't find referenced field 'int error_over_original_count' in program class com.zhihu.matisse.R$string
Warning: com.zhihu.matisse.ui.MatisseActivity: can't find referenced field 'int error_over_original_size' in program class com.zhihu.matisse.R$string
Warning: com.zhihu.matisse.ui.MatisseActivity: can't find referenced field 'int error_over_original_count' in program class com.zhihu.matisse.R$string
```

**Comment by lujing5873** [comment]
我也一样  老哥 搞定了吗 加个qq联系啊  743566091

**Comment by zacharyyy** [comment]
any updates on this?

**Comment by REBOOTERS** [comment]
custom strings would be a good feature .  If you can open a PR about this ,it's welcomed.

**Comment by zacharyyy** [comment]
I've pulled the code and I'll see what it would take to make custom strings work.

@REBOOTERS - there is certainly still an issue with strings and proguard in latest 0.5.2-beta1

**Comment by REBOOTERS** [comment]
#446

**Comment by polaris0227** [comment]
In the file - com.zhihu.matisse.internal.model.SelectedItemCollection
change like below:
`public IncapableCause isAcceptable(Item item) {
            ... ...
            try {
                cause = mContext.getResources().getQuantityString(
                        R.plurals.error_over_count,
                        maxSelectable,
                        maxSelectable
                );
            } catch (NoClassDefFoundError e) {   **// change from "Resources.NotFoundException"**
                cause = mContext.getString(
                        R.string.error_over_count,
                        maxSelectable
                );
            }`

**Comment by sevodnia** [comment]
The problem is that plurals is not defined in the default configuration. Just go to values/string.xml and replace this string with:
     <plurals name="error_over_count">
        <item quantity="one">You can only select up to %1$d media file</item>
        <item quantity="few">You can only select up to %1$d media files</item>
        <item quantity="many">You can only select up to %1$d media files</item>
        <item quantity="other">You can only select up to %1$d media files</item>
    </plurals>
