### ISSUE TITLE
拍照权限 CAMERA PERMISSION

### ISSUE THREAD

**Issue by duanwencheng** [zhihu/Matisse#426]
Demo中不需要拍照权限就可以调用系统相机，我把library以module的形式集成到项目中，如果不申请拍照权限就会permission denial，加了拍照权限可以正常运行。

**Comment by REBOOTERS** [comment]
Matisse 只是打开了系统相机这个 APP，而不是主动去调用 系统相机，请搞清楚这是两件事。至于你在自己的项目中如何使用，那就就你的自由了。
