### ISSUE TITLE
Activity is destroyed when taking a picture

### ISSUE THREAD

**Issue by Peter-Emad** [zhihu/Matisse#432]
When using this library on a Samsung Note 3 device (Samsung devices generally) , the device rotates after taking a picture (default device behavior) so it destroys the activity and the resulting image is lost, so if you could add:
android:configChanges="orientation|screenSize|keyboardHidden" to the the "MatisseActivity" it would solve this issue.

Thanks

**Comment by REBOOTERS** [comment]
Use restrictOrientation(@ScreenOrientation int orientation) to set the desired orientation of image selecting and previewing Activity.

**Comment by Peter-Emad** [comment]
I've tried doing that but the issue still remains on Samsung devices only.

https://stackoverflow.com/questions/16014930/android-activity-getting-destroyed-after-calling-camera-intent

https://stackoverflow.com/questions/10411009/activity-killed-oncreate-called-after-taking-picture-via-intent

**Comment by REBOOTERS** [comment]
ok, I will fix this in the next version.

**Comment by REBOOTERS** [comment]
you can try with latest release to verify this issue.
