### ISSUE TITLE
屏幕息屏解锁时，相册界面会出现重新加载并且伴随闪烁的现象

### ISSUE THREAD

**Issue by fuhaodev** [zhihu/Matisse#433]
### 运行环境 ###

- [x] 设备型号：小米6
- [x] 设备系统版本：Android 8.0
- [x] Gradle 版本：4.4
- [x] Matisse 版本：v0.5.1-beta1

### 具体问题描述 ###
在相册界面也就是MatisseActivity界面，屏幕息屏解锁时，界面会出现重新加载并且伴随闪烁的现象，跳转到预览界面，按Back键返回时也会出现这种情况。

### 原因分析 ###
通过打Log发现，在屏幕息屏解锁时，也就是界面onStart时，LoaderManager.LoaderCallbacks中的onLoadFinished会再次回调，也就导致MatisseActivity中MediaSelectionFragment重新加载，导致界面出现闪烁，怀疑可能是系统SDK的Bug。

**Comment by lucazin** [comment]
not work this.

When i scroll and preview some image and back ..restart from top... ..not saving scroll position
