### ISSUE TITLE
Missing Default String for error_over_original_count and error_over_original_size

### ISSUE THREAD

**Issue by venkat20390** [zhihu/Matisse#441]
**Describe the bug**
The default English translation for error_over_original_count and error_over_original_size in the values/strings.xml. These two values exist only in values-zh/strings.xml. It causes warnings while building gradle and issues while generation signed APK file. This issue occurs only in the latest stable version.

**To Reproduce**
1. Add the latest stable version of the library in Gradle.
2. Build the project.
3. Build completes with two warning regarding the missing default translations.

**Expected behavior**
The Gradle build to complete without any missing default translation warning.

**Comment by REBOOTERS** [comment]
@venkat20390 sorry for the trouble. I'm to busy to supply translation valuse for strings in different language. Anyone could do this, PR is welcomed.

**Comment by venkat20390** [comment]
@REBOOTERS I have submitted a PR for it.

**Comment by REBOOTERS** [comment]
@venkat20390  great job ,I will review the PR as soon as possible .

**Comment by REBOOTERS** [comment]
@venkat20390  resolved in release 0.5.2-beat2
