### ISSUE TITLE
添加依赖问题

### ISSUE THREAD

**Issue by duckmoon** [zhihu/Matisse#444]
implementation 'com.zhihu.android:matisse:$latest_version'
添加依赖后同步报错
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.zhihu.android:matisse:$latest_version.

**Comment by REBOOTERS** [comment]
latest version mean the latest release version .  such as 0.5.1-beta1  .

**Comment by duckmoon** [comment]
implementation 'com.zhihu.android:matisse:0.5.1-beta1', i have tried this, but it did not work yield.

![8c5e6aa2-f39c-4cc7-8ad1-6db706a3d52c](https://user-images.githubusercontent.com/5018105/43175320-14bfa836-8ff1-11e8-8ad9-c97d45dd8e6c.png)

**Comment by REBOOTERS** [comment]
checkout your Internet connection ,

**Comment by duckmoon** [comment]
Have you met that situation caused of internet connection , would you like give me some tips? I have suffered for this about two days. Now, it can't get any dependencies that didn't load before!

**Comment by duckmoon** [comment]
I have tried every you said, it seems something wrong with my Android Studio, because i use another compute with Android Studio load the last matisse version and other  libraries,  all can load success.
  It seems my Android Studio  have set proxy, and i find this:
![image](https://user-images.githubusercontent.com/5018105/43255596-de960c3e-90fc-11e8-8b70-11ff2b0cb750.png)
so, i set the http proxy item with no proxy, but it still doesn't work. I guess it may be the trouble， but  i don't know how to fix it now, do you have any idea? hope for help, Thanks!

**Comment by duckmoon** [comment]
it seems  "mirrors.opencas.cn:80" is the proxy, but i don't know where is it. Maybe the final method is to reinstall studio 😓， whatever thanks for you!

**Comment by duckmoon** [comment]
Very glad to tell you , i have solved the problem. The  reason is i really set proxy from here:
![image](https://user-images.githubusercontent.com/5018105/43301057-5b6794ce-9195-11e8-9e69-3b0baf86d432.png)
but when you disable the proxy, it doesn't work when you only uncheck it, you must comment the proxy in %GRADLE_USER_HOME%\gradle.properties file, not the project's gradle.properties, like this 
![image](https://user-images.githubusercontent.com/5018105/43301222-59eab94a-9196-11e8-88be-50ddfe2c1912.png)

Thank you very much!

**Comment by REBOOTERS** [comment]
haha ,Cool !   Very glad to learn this problem .

It must be Android Studio's Bug .
