### ISSUE TITLE
类型不同如何再界面不展示它

### ISSUE THREAD

**Issue by m733338844** [zhihu/Matisse#445]
比如 Matisse.choose(EnumSet.of(MimeType.PNG))
做些什么才能在recyclerView中不展示不符合类型的数据呢

**Comment by REBOOTERS** [comment]
不符合类型的数据 ？ 是说非 PNG  类型的媒体文件？那直接在 choose 中指定所有你需要的类型，把 PNG 排除在外不就可以了吗？ 

如果你的意思是想通过 choose 方法实现反向筛选，暂时不支持这样的功能。

**Comment by zhuoshirong** [comment]
见意增加 choose(MimeType.ofImage()，列表只展示图片，就不展示视频类；

**Comment by REBOOTERS** [comment]
@zhuoshirong  现在有这个方法的

**Comment by zhuoshirong** [comment]
@m733338844   这个 Matisse.from(SampleActivity.this) .choose(MimeType.ofImage())增加一行  _.showSingleMediaType(true)这样只能保证展示图片的类型，视频类型的就不会显示在列表里面了_

**Comment by zhuoshirong** [comment]
@REBOOTERS 你说的方法是什么方法

**Comment by REBOOTERS** [comment]
MimeType.ofImage() 这个问题，你的问题是什么？  @zhuoshirong

**Comment by AliceZhuZhu** [comment]
我有类似的问题  如果我指定了用户可选择的类型是png和MP4格式  那其他类型的视频或者图片可不可以不显示在列表中？

**Comment by didikee** [comment]
感觉问题还没解决，这个issue不应该关闭，或者作者直接说不支持该特性好了

**Comment by REBOOTERS** [comment]
Matisse.from(SampleActivity.this) .choose(MimeType.ofImage()).showSingleMediaType(true)

可以保证只显示所有图片，不显示视频。

 Matisse.from(SampleActivity.this) .choose(MimeType.ofVideo()).showSingleMediaType(true)

可以保证只显示所有视频，不显示图片。

但现在并不支持从更精细的维度，比如 jpg,png 做区分.

@didikee

**Comment by REBOOTERS** [comment]
不知道这种场景是否很多，如果多的话，可以考虑支持。

**Comment by didikee** [comment]
@REBOOTERS 其实不少的。

在图片中，JPG和PNG是常规支持的，这个是主流。但是GIF和JPG/PNG 差别很大，一般都会专门把GIF过滤掉，特别对于照片视频编辑类软件而言，GIF和普通图片混在一起很麻烦。

我自己最近的项目中有一个图片选择功能，目的是只选择动图GIF。但是目前这个库并不能做到这一点。

我相信这个库无论是从易用性、健壮性、美观上都要优于我自己短时间去写一个图片选择模块要好，但最后我还是只能自己去写一个。

在初次使用的时候我指定了JPG、PNG，但是结果中包含了其他格式的图片，我以为是bug，在查询不少issue之后才发现这是特性😂，希望能做到指定哪些类型就显示哪些类型吧，不然展示出来用户点击了又提示不支持确实不太好（用户或许会想，不支持干嘛放在这里，我第一次使用就是这么想的😂）

如果能支持的话我就再迁会这个库了，感谢！
