### ISSUE TITLE
切换相册 相册图片加载不出来

### ISSUE THREAD

**Issue by iceuncle** [zhihu/Matisse#447]
切换相册后 相册图片加载不出来，需要滑动后才会显示

**Comment by REBOOTERS** [comment]
@iceuncle  是相册中新增图片没有加载出来吗？

**Comment by iceuncle** [comment]
不是的，是在切换相册后，再次点开spinner，popwindow里的图片没有加载出来

**Comment by PineappleM** [comment]
这个貌似还没解决噻

**Comment by PineappleM** [comment]
啥时候可以解决这个bug否？

**Comment by REBOOTERS** [comment]
暂时没有复习，不知道是什么原因。

**Comment by REBOOTERS** [comment]
是某个特定的相册，还是说所有相册都会有问题 ？

**Comment by PineappleM** [comment]
所有的，感觉是视图刷新的问题，就是点击那个相册选择一个新相册后，再点击相册选择popupwindow就没有图片预览了，然后重新点击打开一下popupwindow就有预览图了

**Comment by fuhaodev** [comment]
同样遇到了这个问题，切换一个相册，再次点击弹出popup，图片就不显示了，必须要滑动一下才刷新。
![wechatimg509](https://user-images.githubusercontent.com/17568641/43709635-e751f54e-999f-11e8-8019-07a80d1725c4.png)

**Comment by REBOOTERS** [comment]
OK ,问题已知，会尽快修复 。

**Comment by yuxingxing1988** [comment]
这个问题改好了 通知一声啊

**Comment by REBOOTERS** [comment]
嗯，修复后会通知 @yuxingxing1988

**Comment by zouyuanfeng** [comment]
目前发现是RoundedRectangleImageView#onDraw()  的canvas.clipPath(mRoundedRectPath);导致的问题。注释之后 就没问题了，只是圆角矩形也变回正常的ImageView了

**Comment by gdhy-xh** [comment]
这个bug貌似还没修复好呢？现在突然出现了，请帮忙处理

**Comment by daixu** [comment]
> 这个bug貌似还没修复好呢？现在突然出现了，请帮忙处理

我这边这两天也发现了这个bug。我这边排查了一番发现把项目中的androidx.appcompat:appcompat的版本给降低到1.2.0及以下，切换目录的时候就能显示正常，如果大于1.2.0的版本切换就是空白的。你那边也可以试一下把这个改动看一下有没有效果。
