### ISSUE TITLE
图片展示列表，能把视频类的文件过滤不显示吗

### ISSUE THREAD

**Issue by zhuoshirong** [zhihu/Matisse#448]
Matisse.from(SampleActivity.this).choose(MimeType.ofImage())，您好，有办法能把视频类的文件过滤不展示在列表里面吗，通过choose只是过滤了选择，但是还是展示了视频类的文件；

**Comment by REBOOTERS** [comment]
@zhuoshirong  被展示的视频是普通的 mp4 格式的吗？ 可以的话请提供一下 视频格式编码信息

**Comment by zhuoshirong** [comment]
Matisse.from(SampleActivity.this) .choose(MimeType.ofImage())可以我找到你的API了，增加一个  .showSingleMediaType(true)选择这样就可以不显示视频，只展示图片的类型了，谢谢

**Comment by REBOOTERS** [comment]
releated issue #445
