### ISSUE TITLE
为什么我的选择相册有黑边

### ISSUE THREAD

**Issue by BigSweet** [zhihu/Matisse#450]
![image](https://user-images.githubusercontent.com/18210031/43244125-2fbd0b4c-90dc-11e8-812b-1bc5b132a478.png)

**Comment by REBOOTERS** [comment]
wow ,it's strange ,which device ?

**Comment by BigSweet** [comment]
应该和设备没关系，可能是和主题有关系？我用你们的官方demo是没黑边的，但是引入到我的APP里面就会有黑边。自己也没找到原因，所以来问下

**Comment by BigSweet** [comment]
这个popwindows是你们库中的东西，所以我来问下，是否是因为什么操作，导致会影响到这个列表页

**Comment by BigSweet** [comment]
ok 我解决了，album_list_item布局中添加背景android:background="#ffffff"
同时mListPopupWindow.setBackgroundDrawable(new ColorDrawable());
黑边消失，但是这是在我改你们库中的源代码的情况下修复的，具体引起原因暂时不清楚

**Comment by REBOOTERS** [comment]
1. ListPopupWindow  是 Android  官方 support 库中提供的，并不是我们自己的实现。
2. 如果你自定义 style ，是否设置了 listPopupWindowStyle 的值呢？ 具体可参考源码中 styles 下 Theme.Zhihu 和 Theme.Dracula 两个主题的实现
3. 如果你遵循了 style 定义的规则，完整定义了所有值，是不用修改源码的。

**Comment by BigBigDeBoy** [comment]
现在解决了吗

**Comment by parkwookdong** [comment]
经测试，zhihu_album_popup_bg这个颜色值的不透明度只要不设置FF，就不会有黑边了，还没找到原因
