### ISSUE TITLE
来自项目中两个Exception

### ISSUE THREAD

**Issue by Microhx** [zhihu/Matisse#451]
1. Item类mimeType 获取时为null
`
return new Item(cursor.getLong(cursor.getColumnIndex(MediaStore.Files.FileColumns._ID)),
                cursor.getString(cursor.getColumnIndex(MediaStore.MediaColumns.MIME_TYPE)),
                cursor.getLong(cursor.getColumnIndex(MediaStore.MediaColumns.SIZE)),
                cursor.getLong(cursor.getColumnIndex("duration")));
`
此时需要在Item类中判断：
`
cursor.getString(cursor.getColumnIndex(MediaStore.MediaColumns.MIME_TYPE)) 为null
`
这里需要判断一下：
`
private Item(long id, String mimeType, long size, long duration) {
        this.id = id;
        this.mimeType = mimeType == null ? "unKnow" : mimeType;
       //....
}
`

2. MediaSelectionFragment中
`
 mRecyclerView.setLayoutManager(new GridLayoutManager(getContext(), spanCount));
`
bugly上报说明spanCount为0，因为这里需要重写一下：
`
mRecyclerView.setLayoutManager(new GridLayoutManager(getContext(), spanCount < 1 ? 3 : spanCount));
`

以上错误均来自线上bugly提交，如果需要机型，请留言。

**Comment by REBOOTERS** [comment]
不知道你用的是什么版本？ 

问题1 ， 关于 mimeType  ==  null ，内部使用均有判断
问题2. ， 通过  spanCount 的写操作可以发现，如果你没有配置 gridExpectedSize ，默认值为 3， 如果你配置了 gridExpectedSize ，会根据这个值等分屏幕宽取一个合适的值，最小也会是1 。

**Comment by hongyanfengzi** [comment]
![image](https://user-images.githubusercontent.com/17542412/43445902-13fc54ce-94da-11e8-9465-660948f7b579.png)
有个地方没判断, 还抛出异常了 Item类的isGig()方法  0.4.3版本

**Comment by REBOOTERS** [comment]
这个很早之前就修复了。
