### ISSUE TITLE
打开Matisse  返回报错

### ISSUE THREAD

**Issue by yishangfei** [zhihu/Matisse#452]
![image](https://user-images.githubusercontent.com/15099278/43434531-a36cac66-94ae-11e8-809b-f0798a9781ca.png)

![image](https://user-images.githubusercontent.com/15099278/43434544-afe136b0-94ae-11e8-89a0-c365acf39eff.png)
进入Matiss点返回按键  和toolbar的返回都会包这个错   选中点确定是能获取到图片地址 不报错

**Comment by REBOOTERS** [comment]
这个很明显是你的 MineFragment.kt 的 onActivityResult 里包的错，和 Matisse没有关系。
