### ISSUE TITLE
android.database.StaleDataException:Attempted to access a cursor after it has been closed.

### ISSUE THREAD

**Issue by windin** [zhihu/Matisse#456]
Caused by:
--
5 android.database.StaleDataException:Attempted to access a cursor after it has been closed.
6 android.database.BulkCursorToCursorAdaptor.throwIfCursorIsClosed(BulkCursorToCursorAdaptor.java:63)
7 android.database.BulkCursorToCursorAdaptor.getCount(BulkCursorToCursorAdaptor.java:69)
8 android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
9 android.database.AbstractCursor.moveToNext(AbstractCursor.java:268)
10 android.database.CursorWrapper.moveToNext(CursorWrapper.java:202)
11 com.zhihu.matisse.internal.ui.AlbumPreviewActivity.onAlbumMediaLoad(AlbumPreviewActivity.java:71)
12 com.zhihu.matisse.internal.model.AlbumMediaCollection.onLoadFinished(AlbumMediaCollection.java:64)
13 com.zhihu.matisse.internal.model.AlbumMediaCollection.onLoadFinished(AlbumMediaCollection.java:33)

Caused by:
--
5 android.database.StaleDataException:Attempted to access a cursor after it has been closed.
6 android.database.BulkCursorToCursorAdaptor.throwIfCursorIsClosed(BulkCursorToCursorAdaptor.java:63)
7 android.database.BulkCursorToCursorAdaptor.getCount(BulkCursorToCursorAdaptor.java:69)
8 android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
9 android.database.AbstractCursor.moveToNext(AbstractCursor.java:268)
10 android.database.CursorWrapper.moveToNext(CursorWrapper.java:202)
11 com.zhihu.matisse.internal.ui.AlbumPreviewActivity.onAlbumMediaLoad(AlbumPreviewActivity.java:71)
12 com.zhihu.matisse.internal.model.AlbumMediaCollection.onLoadFinished(AlbumMediaCollection.java:64)
13 com.zhihu.matisse.internal.model.AlbumMediaCollection.onLoadFinished(AlbumMediaCollection.java:33)

**Comment by REBOOTERS** [comment]
#423
