### ISSUE TITLE
作者可不可以把只启动手机进行拍照的api开放出来?

### ISSUE THREAD

**Issue by Freedomhxb** [zhihu/Matisse#457]
如题,非常感谢.

**Comment by REBOOTERS** [comment]
只是一个图片选择器，只是顺带了拍照功能。如果想直接进行拍照，打开相机即可。

**Comment by REBOOTERS** [comment]
#406

**Comment by zybooo1** [comment]
`   mediaStoreCompat= new MediaStoreCompat(this);
       mediaStoreCompat.setCaptureStrategy(new CaptureStrategy(true, Constants.PROVIDER_AUTHORITY));
       mediaStoreCompat.dispatchCaptureIntent(this, REQUEST_CODE_CAMERA);`


`if (requestCode == REQUEST_CODE_CAMERA&& resultCode == RESULT_OK) {
            String contentPath = mediaStoreCompat.getCurrentPhotoPath();
        }`

我这样使用

**Comment by LXLYHM** [comment]
同感，要是有单独拍照和单独获取相册的功能更加锦上添花 嘻嘻~
