### ISSUE TITLE
Videos?

### ISSUE THREAD

**Issue by sasa0** [zhihu/Matisse#46]
You stated this is image and video selecting gallery, but I cannot see videos. In the MimeType enum, I only see images...

**Comment by gejiaheng** [comment]
@sasa0 
Sorry for your confusion. Last public release version 0.4.3 only supports image. And the latest master branch supports image and video but not quite prepared for v0.5 release. I'll release v0.5 in a few days.

You can check out the latest [MimeType.java](https://github.com/zhihu/Matisse/blob/master/matisse/src/main/java/com/zhihu/matisse/MimeType.java) for more details about media types Matisse supports.

**Comment by sasa0** [comment]
Thank you for the clarification. Your project looks awesome.
