### ISSUE TITLE
Crash if user try to select more than maxSelectable() param

### ISSUE THREAD

**Issue by jhionan** [zhihu/Matisse#462]
if I mark any number at maxSelectable and the user try to select one more, the app crashes instead of not showing a a friendly message of not allowed

**Comment by REBOOTERS** [comment]
Did this happened in latest version ?

**Comment by agnoam** [comment]
> No, I was using tha last stable.
> 
> I tried beta now and its already solved..
> 
> Tks

Which version is it ?
