### ISSUE TITLE
Android P 中 getSupportLoaderManager 已经被弃用

### ISSUE THREAD

**Issue by Lee-Wang-Jing** [zhihu/Matisse#463]
Android P 中 getSupportLoaderManager 已经被弃用

**Comment by REBOOTERS** [comment]
还好吧，虽然在 android.app 包下被 deprecated 了，但是 android.support.v4.app 包下还是支持的，而且这也可能是官方的意图，想把这个类移到 support 包中去维护了。这个库里用的也一直是 support 包下的，所以应该没有什么问题。

**Comment by may1112** [comment]
我现在升级到androidx 调用的时候报错  找不到的这个接口方法 不知道怎么解决

**Comment by REBOOTERS** [comment]
有 log 吗 ？
