### ISSUE TITLE
预览图片黑屏，内存好像一直没有回收，短时间Native申请大量内存导致内存溢出

### ISSUE THREAD

**Issue by MarkRaoAndroid** [zhihu/Matisse#465]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

Matisse.from(MainActivity.this)
        .choose(MimeType.allOf())
        .countable(true)
        .maxSelectable(9)
        .addFilter(new GifSizeFilter(320, 320, 5 * Filter.K * Filter.K))
        .gridExpectedSize(getResources().getDimensionPixelSize(R.dimen.grid_expected_size))
        .restrictOrientation(ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED)
        .thumbnailScale(0.85f)
        .imageEngine(new GlideEngine())
        .forResult(REQUEST_CODE_CHOOSE);
我在依赖gradle后，直接复制这段代码，但是GifSizeFilter无法找到，然后我删除了addFilter，然后预览图片黑屏，打开源码发现GifSizeFilter居然不是public的，这是为何啊？？？

**Comment by MarkRaoAndroid** [comment]
把GifSizeFilter复制出来并申明为public，预览图片问题解决

**Comment by REBOOTERS** [comment]
Filter 是一种过滤策略，你可以自己定义自己的 Filter ，demo 里提供的Filter只是一个参考。
