### ISSUE TITLE
Update to Glide 4.8

### ISSUE THREAD

**Issue by pvegh** [zhihu/Matisse#466]
This lib needs glide 3.8.0, thus we cannot use this in our project which is using Glide 4.8.
We cannot downgrade, and it would be correct if the library would use the latest glide version.

1. Update glide dependency to 4.8.0
2. Use a library function
3. crash:
java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager'

**Comment by REBOOTERS** [comment]
please read the readme

**Comment by pvegh** [comment]
Glide v4 is over a year old. When do you think is it time to drop the old API and support only v4?
You could write an abstraction if you are really into that kind of thing, but maybe the correct way is to switch to the 1 year old "new" API instead of forcing apps to use the old one.
Lazy projects can still use the old version of Matisse until they are ready to upgrade.

**Comment by ParitoshVaidya** [comment]
As mentioned in **Read Me**, copy the code available at link: [Glide4Engine](https://github.com/zhihu/Matisse/blob/master/sample/src/main/java/com/zhihu/matisse/sample/Glide4Engine.java)

and change the code to:

    .imageEngine(Glide4Engine()) // for kotlin
    .imageEngine(new Glide4Engine()) // for java

**Comment by PeterXiaosa** [comment]
The Glide4Engine is 404...
