### ISSUE TITLE
Can I take more than one photo?

### ISSUE THREAD

**Issue by hksfho** [zhihu/Matisse#471]
can i take more than one photo?

**Comment by REBOOTERS** [comment]
Android  Camera can do this ? take more than one photo at once ?

**Comment by hksfho** [comment]
I mean dont return immediately

**Comment by REBOOTERS** [comment]
I understand what you want . 

you can start  Camera , take picture and save it temporary at some place ,then take another .
at last ,use all picture which has been saved .  you can do all of this without matisse .

Matisse is focus on select media which include picture and video from photo  right now .

**Comment by hksfho** [comment]
thx, I am going to implement my own camera haha
