### ISSUE TITLE
How to show camera option?

### ISSUE THREAD

**Issue by Swati4star** [zhihu/Matisse#473]
I am using this to invoke Matisse activity
```
Matisse.from(this)
                .choose(MimeType.ofAll(), false)
                .countable(true)
                .maxSelectable(1000)
                .imageEngine(new PicassoEngine())
                .forResult(INTENT_REQUEST_GET_IMAGES);
```

The UI looks like this:
<img width="336" alt="screen shot 2018-08-29 at 8 28 29 pm" src="https://user-images.githubusercontent.com/9164477/44796202-1e9ab900-abca-11e8-9868-184500c26546.png">
@REBOOTERS 

How do I open up camera option also? ( as shown in this image : https://github.com/zhihu/Matisse/blob/master/image/screenshot_zhihu.png )

**Comment by REBOOTERS** [comment]
use capture and captureStrategy method , more details you can find in sample project.
