### ISSUE TITLE
how to pre selected?

### ISSUE THREAD

**Issue by hksfho** [zhihu/Matisse#475]
Can I pass a Uri array list for per selected?

**Comment by REBOOTERS** [comment]
the feature has not supported.

**Comment by Swati4star** [comment]
Isn't it same as https://github.com/zhihu/Matisse/issues/472 ?

**Comment by hksfho** [comment]
yes, same with you

**Comment by fishkingsin** [comment]
@hksfho https://github.com/nixplay/Matisse/tree/feature/remember_selection
