### ISSUE TITLE
7.0手机点击拍照会崩溃，需要相机权限

### ISSUE THREAD

**Issue by LebronXia** [zhihu/Matisse#477]
Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.android.camera2/com.android.camera.CaptureActivity clip={text/uri-list U:content://com.balance.zhiren.test.fileProvider/my_images/JPEG_20180905_120821.jpg} (has extras) } from ProcessRecord{491300d 4520:com.balance.zhiren.test/u0a68} (pid=4520, uid=10068) with revoked permission android.permission.CAMERA

这个库里面需要相机权限，但看例子没看到哪个地方添加了相机权限，求解答

**Comment by REBOOTERS** [comment]
请详细说明问题？ 手机型号，版本，你这样提问有什么价值？

**Comment by LebronXia** [comment]
用的是华为mate10.Android8.1.0 的系统，点击拍照会出现需要相机权限的报错，这是要在哪里添加这个权限申请

**Comment by REBOOTERS** [comment]
使用相机并一定要使用  Camera 权限，可以参考 https://github.com/zhihu/Matisse/issues/457#issuecomment-413448395
