### ISSUE TITLE
希望增加已选择图片进入默认选中的功能。

### ISSUE THREAD

**Issue by KuangGang** [zhihu/Matisse#482]
情景：
选择图片以后用户发现选的图片不对，且所选图片数量没有达到上限。
重新进入选择图片之前选中的图片默认选中，点击取消勾选。

是否可以通过保存的uri来进行实现？在builder构造中加入List<Uri>参数？
只是一个建议，看了半天结果没有这个功能，就只能弃掉了。
希望越来越好！

**Comment by REBOOTERS** [comment]
#472

**Comment by daleiyinsi** [comment]
我也是，没有这个功能，放弃了
