### ISSUE TITLE
调用 Unable to start activity ComponentInfo{com.mohu.qianqian/com.zhihu.matisse.ui.MatisseActivity}: java.lang.IllegalStateException: Only fullscreen activities can request orientation

### ISSUE THREAD

**Issue by hufu4635** [zhihu/Matisse#484]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hufu4635** [comment]
在android 8.0出现 该异常

**Comment by REBOOTERS** [comment]
how to reproduce this issue ? you select issue template ,why not use it ?

**Comment by hufu4635** [comment]
把APP主题里的设置这些注释掉 就不会出现这个异常了  ，已解决

**Comment by hufu4635** [comment]
``
