### ISSUE TITLE
build relesse版本的时候，混淆报错了

### ISSUE THREAD

**Issue by gaojuanjuan** [zhihu/Matisse#485]
Warning: com.zhihu.matisse.engine.impl.GlideEngine: can't find referenced method 'com.bumptech.glide.DrawableTypeRequest load(android.net.Uri)' in program class com.bumptech.glide.RequestManager

**Comment by REBOOTERS** [comment]
你是怎么配置的呢？

**Comment by gaojuanjuan** [comment]
是Glide的版本问题，我改成了使用3.0的引擎
