### ISSUE TITLE
Select multiple type files

### ISSUE THREAD

**Issue by azizarc88** [zhihu/Matisse#494]
Why i cannot select multiple files with multiple type ?
example, i want to select image with video

Did you do this to avoid some bug ?

**Comment by REBOOTERS** [comment]
choose images and videos at same time had been supported.

`
    public SelectionCreator choose(Set<MimeType> mimeTypes, boolean mediaTypeExclusive) {
        return new SelectionCreator(this, mimeTypes, mediaTypeExclusive);
    }
`
mediaTypeExclusive = false .
