### ISSUE TITLE
状态栏被挡住

### ISSUE THREAD

**Issue by HeQuanLi** [zhihu/Matisse#495]
![qq 20181008160538](https://user-images.githubusercontent.com/7410469/46597775-15c7cc00-cb14-11e8-8919-0600fb05adec.png)

**Comment by HeQuanLi** [comment]
我当前activity是有的，我在想你要不把你的每个activity加上这个属性？

**Comment by REBOOTERS** [comment]
@HeQuanLi  是什么系统和手机？

**Comment by HeQuanLi** [comment]
三星S8

**Comment by HeQuanLi** [comment]
三星S8  Android 8.0和华为P9 Android8.0

**Comment by REBOOTERS** [comment]
你想实现什么样的效果呢?

**Comment by HeQuanLi** [comment]
因为我要做沉侵式状态栏，所以在我所有的activity样式中加了
`        <item name="android:windowTranslucentStatus">true</item>
        <item name="android:windowTranslucentNavigation">true</item>`

**Comment by REBOOTERS** [comment]
沉寝式状态栏对不同版本是需要适配的，你这么写不一定OK。推荐 https://github.com/laobie/StatusBarUtil
