### ISSUE TITLE
Android 4.1版本 java.lang.RuntimeException 【bug】

### ISSUE THREAD

**Issue by MyAndroidStore** [zhihu/Matisse#496]
java.lang.RuntimeException:Unable to start activity ComponentInfo{xxx.xxx.xxx/com.zhihu.matisse.ui.MatisseActivity}: android.view.InflateException: Binary XML file line #76: Error inflating class com.zhihu.matisse.internal.ui.widget.CheckRadioView

我看了下 是否是用了webp格式图片 而Android4.1并不兼容

**Comment by REBOOTERS** [comment]
duplicate with #474
