### ISSUE TITLE
Unable to load class 'org.gradle.api.internal.component.Usage'

### ISSUE THREAD

**Issue by naivor** [zhihu/Matisse#51]
gradle 失败，下面是log,请问这个这么破

```
Error:Unable to load class 'org.gradle.api.internal.component.Usage'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
```

**Comment by gejiaheng** [comment]
@naivor   
Have your local project recovered? I think the console log gave us some hints.  
If you're still in trouble, try `./gradlew clean` or `./gradlew cleanBuildCache` or restart AS. After that, rebuild your project. I'm not sure but this may help.

**Comment by naivor** [comment]
Thanks,I have solved this problem! This problem appears because the gradle i used 's  version  is 3.4.1,and   it is  not  compatible with the plugin  'com.novoda:bintray-release:0.4.0' 's  gradle version,when i  upgrade it  to  0.5.0,it  works.

**Comment by muhammad17574** [comment]
navior solution workout for me in android 3.0 thanks dude

**Comment by shrivastavaanurag** [comment]
thanks navior. it works

**Comment by Longalei** [comment]
yeah   thanks navior .

**Comment by Longalei** [comment]
it can [https://github.com/novoda/bintray-release](the url to bintray)help you to solve the problem

**Comment by djalmaafilho** [comment]
It souved my problem, thanks
