### ISSUE TITLE
MimeType.ofImage() doesn't work as expected

### ISSUE THREAD

**Issue by yccheok** [zhihu/Matisse#516]
**Describe the bug**
When we use `MimeType.ofImage()`, we expect only image files will be shown. However, we notice that, video files are also shown

**To Reproduce**
I'm using the following code

        Matisse.from(this)
                .choose(MimeType.ofImage())
                .countable(true)
                .maxSelectable(Integer.MAX_VALUE)
                .imageEngine(new Glide4Engine())
                .thumbnailScale(1.0f)
                .forResult(REQUEST_CHOOSE_IMAGE);

**Expected behavior**
We expect only image files is shown. 

However, as in screenshots, you can see video files is displayed as well.

If I select the video files, toast message "不支援的文件类型" will be shown.

**Screenshots**
<img width="540" alt="device-2018-10-26-163941" src="https://user-images.githubusercontent.com/308276/47555543-aa1c9600-d93e-11e8-967e-24812c1f92b3.png">

**Smartphone (please complete the following information):**
XiaoMi A1, Android 8.1.0

**Additional context**

**Comment by wys619** [comment]
try this, it will be helpful .

showSingleMediaType(true)

**Comment by yccheok** [comment]
Thanks. It helps.
