### ISSUE TITLE
点击看大图时奔溃

### ISSUE THREAD

**Issue by hbzkw** [zhihu/Matisse#54]
![default](https://cloud.githubusercontent.com/assets/10335430/25950177/9e8bdb62-368c-11e7-989f-0cfcdb9c61ec.png)
您好  为什么选择图片的界面 不报theme的错误   而看大图的界面却报错？

**Comment by gejiaheng** [comment]
@hbzkw 
Thanks for reporting this bug. I found that I forgot to set `AlbumPreviewActivity` and `SelectedPreviewActivity`'s theme. What is your phone's Android os version?

**Comment by gejiaheng** [comment]
@hbzkw 
I don't have devices to reproduce this crash. But I may have fixed it, check out https://github.com/zhihu/Matisse/pull/61. You can reopen this issue if this crash still happen.
