### ISSUE TITLE
返回照片列表页，列表页会刷新到顶部

### ISSUE THREAD

**Issue by Freedomhxb** [zhihu/Matisse#543]
就是当你预览完照片后，返回照片列表页，列表页会刷新到顶部。

**Comment by xingxing16** [comment]
对啊，这个问题修复没有，有点难受

**Comment by xingxing16** [comment]
就是你预览图片，然后返回会返回图片列表顶部，不会记住上次滑动到的位置



---原始邮件---
发件人: "Rookie"<notifications@github.com&gt;
发送时间: 2019年11月1日(星期五) 上午9:06
收件人: "zhihu/Matisse"<Matisse@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"xingxing16"<2459014429@qq.com&gt;;
主题: Re: [zhihu/Matisse] 返回照片列表页，列表页会刷新到顶部 (#543)



Closed #543.

**Comment by xingxing16** [comment]
方便加个联系方式吗？我发视频给你看看



---原始邮件---
发件人: "Rookie"<notifications@github.com&gt;
发送时间: 2019年11月1日(星期五) 上午9:06
收件人: "zhihu/Matisse"<Matisse@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"xingxing16"<2459014429@qq.com&gt;;
主题: Re: [zhihu/Matisse] 返回照片列表页，列表页会刷新到顶部 (#543)



Closed #543.

**Comment by xingxing16** [comment]
请问该怎么修复呀

**Comment by Freedomhxb** [comment]
> 请问该怎么修复呀

  implementation 'com.zhihu.android:matisse:0.5.2-beta3'
