### ISSUE TITLE
为什么6.0以上的手机 ，不用申请拍照权限，也能使用相机？这是怎么做到的？

### ISSUE THREAD

**Issue by hyandroid** [zhihu/Matisse#547]
为什么6.0以上的手机 ，不用申请拍照权限，也能使用相机？这是怎么做到的？

**Comment by zqr95518** [comment]
target sdk >= 23 才有权限确认

**Comment by YiMenHuiShou** [comment]
https://blog.csdn.net/gaolh89/article/details/79809034

**Comment by REBOOTERS** [comment]
https://developer.android.com/training/permissions/best-practices?hl=zh-cn

@hyandroid
