### ISSUE TITLE
please! change the button names~~~ 

### ISSUE THREAD

**Issue by maseunghwa** [zhihu/Matisse#568]
i need Matisse package 

you miss the button name   'button_sure'

this button`s korea name   '확인'

please! change the button name!!   thankyou!!!

**Comment by ImaginationRoom** [comment]
Add the following string resources in your project to override it. 

in values-ko/strings.xml (for Korean)
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="button_sure_default">Your preferred text</string>
    <string name="button_sure">Your preferred text(%1$d)</string>
</resources>
```
