### ISSUE TITLE
[Need Help] Only show GIF filter is invalid?

### ISSUE THREAD

**Issue by RealZhangAndAndroid** [zhihu/Matisse#579]
Thank you for your excellent open source library.
How to select only GIF images, do not display any other type of images in the Select Picture interface.
I tried this method to only display images in GIF format but it is invalid, or PNG & JPG will be displayed.

These 2 lines of code are invalid in order to display only GIF images
.choose(MimeType.of(MimeType.GIF))
.showSingleMediaType(true).

Hope you can fix this bug because it means that many good GIF apps will use your library.

**Comment by REBOOTERS** [comment]
v0.5.3-beta1
