### ISSUE TITLE
单选

### ISSUE THREAD

**Issue by bxxasn** [zhihu/Matisse#581]

**Comment by merlin720** [comment]
maxSelectable 这个设置成1就是单选了吧

**Comment by bxxasn** [comment]
单选，如果在选择图片得时候，选多个图片，直接闪退。

**Comment by weichenxu1234** [comment]
我是因为 升级了android studio 3.4.2 ,然后引入方式 改成了api , 单选一张图片,然后再勾选第二张图片 就会闪退.和@bxxasn一样的情况.

**Comment by weichenxu1234** [comment]
好吧 已经解决了, 在'com.zhihu.android:matisse:0.5.2-beta3' 已经解决了
