### ISSUE TITLE
Support on Android Q

### ISSUE THREAD

**Issue by yccheok** [zhihu/Matisse#587]
**Describe the bug**
Google makes drastic changes on storage access permission in Android Q - https://developer.android.com/preview/privacy/scoped-storage#preserve-files-shared-collections Is there any changes required in this library, to make it continue to work as it is?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mthli** [comment]
We will verify and support Android Q as soon as possible.

**Comment by yccheok** [comment]
If you can publish your findings and planned workarounds in the wiki, that will be great. I hope to understand problem, and contribute some code patches if possible.

Thank you very much once again!

**Comment by mthli** [comment]
@yccheok Our our internal engineer check it again, it looks fine with Android Q. So you can check it on your side.

**Comment by yccheok** [comment]
After testing using Android Q emulator, it looks fine. Folders like `Download`, `Camera` still accessible.

<img width="248" alt="x" src="https://user-images.githubusercontent.com/308276/55527023-ead8c200-56c9-11e9-9662-7b870f14aaff.png">

But, I'm not sure whether other apps folder like `WhatsApp Images`, `WeChat`, ... still accessible, as my emulator not able to install those apps.

I think we can close this ticket at this moment. Thank you for paying attention.
