### ISSUE TITLE
An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by TomatoWithEgg** [zhihu/Matisse#589]
代码很简单,XML中一个Button,给Button设置了点击事件.
btn_picker.setOnClickListener {
            Matisse.from(this)
                .choose(MimeType.ofAll())
                .countable(true)
                .maxSelectable(9)
                .gridExpectedSize(120)
                .restrictOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT)
                .thumbnailScale(0.85f)
                .theme(R.style.Matisse_Dracula)
                .imageEngine(GlideEngine())
                .forResult(REQUEST_CODE_CHOOSE)
        }
点击按钮时程序报错
An error occurred while executing doInBackground()

**Comment by RDsanji** [comment]
已解决,需要在之前申请内存读写权限
