### ISSUE TITLE
在 maxSelectable == 1 的时候还是多选状态，感觉这个比较反人类，有计划做单选吗？

### ISSUE THREAD

**Issue by YeungKC** [zhihu/Matisse#6]

**Comment by gejiaheng** [comment]
@YeungKC   
Am I getting this wrong?
The following code snippet is from `SelectionSpecBuilder.forResult(int requestCode)`:  
```java
        if (mMaxSelectable <= 1) {
            mSelectionSpec.countable = false;
            mSelectionSpec.maxSelectable = 1;
        } else {
            mSelectionSpec.countable = mCountable;
            mSelectionSpec.maxSelectable = mMaxSelectable;
        }
```
If you pass `1` to `maxSelectable()` while launching Matisse, you can only choose one image.

**Comment by YeungKC** [comment]
抱歉，可能我描述的不够清楚，我想说的是如果在 maxSelectable == 1，PhotoGrid 的 CheckView 还有出现必要吗？
我感觉连 BottomToolbar 出现的必要都没有了，因为当在 maxSelectable == 1，点击 Thumbnail 的时候就进入 AlbumPreviewActivity 里面确认就够了。

不知道你们觉得怎样~？

**Comment by gejiaheng** [comment]
@YeungKC 
Now I understand what you mean and it's a great proposal. As I am under heavy development of supporting video selecting, give me a few days to think about it.

**Comment by gejiaheng** [comment]
We'll discuss this feature in https://github.com/zhihu/Matisse/issues/55
