### ISSUE TITLE
拍照bug

### ISSUE THREAD

**Issue by leeyun** [zhihu/Matisse#617]
![image](https://user-images.githubusercontent.com/11530379/59032765-a15b4d80-8899-11e9-8719-8378110b5317.png)
```
captureStrategy(CaptureStrategy(true, "${BuildConfig.APPLICATION_ID}.fileprovider", "test"))
```

如果设置directory会执行红框中的代码导致部分机型的手机无法正常生成图片文件
测试设备:redmi7 
系统版本:android9.0

**Comment by leeyun** [comment]
还有关联下 #613   9.0系统不会扫描非相机目录下图片文件应该都是兼容性导致的

**Comment by leeyun** [comment]
非最新版本代码导致拍照问题

**Comment by liuqiangit** [comment]
我这边也是哦  这个拍照策略中的directory 设置test能用，别的都不好使
