### ISSUE TITLE
Could not download matisse.aar 大家都没遇到这个问题吗？

### ISSUE THREAD

**Issue by gaoyong06** [zhihu/Matisse#629]
其他的库，都没问题，就matisse down不下来
大家都没遇到这个问题吗？

Unable to resolve dependency for ':app@qqDebug/compileClasspath': Could not download matisse.aar (com.zhihu.android:matisse:0.5.2-beta3)

**Comment by xybCoder** [comment]
现在maven库也拉不到了

**Comment by REBOOTERS** [comment]
应该是网络原因，不是这个库的问题。
