### ISSUE TITLE
申请完权限仍无法拍照

### ISSUE THREAD

**Issue by xiaowang119** [zhihu/Matisse#634]
**Describe the bug**
java.lang.SecurityException: UID 10550 does not have permission to content://com.zhihu.matisse.sample.fileprovider/my_images/test/JPEG_20190725_173859.jpg [user 0]

**To Reproduce**
点击拍照图标后闪退

**Smartphone (please complete the following information):**
 - Device:MI 5X
 - Version MIUI 10.3

**Comment by xiaowang119** [comment]
已解决~  没写fileprovider的问题

**Comment by caopeng000** [comment]
我写了fileter拍照还是报错，是包名
