### ISSUE TITLE
视频预览问题

### ISSUE THREAD

**Issue by lucers** [zhihu/Matisse#640]
跳转视频选择时,点击播放视频,播放完成时界面崩溃,
![image](https://user-images.githubusercontent.com/20353542/62831423-74d50080-bc51-11e9-862d-75a83431434d.png)

**Comment by lucers** [comment]
我项目里面使用的Matisse是0.5.1版本的

**Comment by REBOOTERS** [comment]
https://github.com/zhihu/Matisse/issues/423
