### ISSUE TITLE
 error: resource previously defined here.

### ISSUE THREAD

**Issue by lindetech** [zhihu/Matisse#647]
Android resource compilation failed
Output:  D:\Android\AndroidStudioProjects\MoveHouse4.0\DriverClient\app\build\intermediates\incremental\mergeAndroidDebugResources\merged.dir\values\values.xml:811: error: duplicate value for resource 'attr/layout_anchorGravity' with config ''.

\mergeAndroidDebugResources\merged.dir\values\values.xml:811: error: resource previously defined here.

经查看应该是与xrecyclerview命名冲突 忘采纳

**Comment by REBOOTERS** [comment]
matisse 内部没有定义 layout_anchorGravity 这个 property ,不懂你说的冲突为什么和这个库有关？

**Comment by lindetech** [comment]
那会不会是xrecyclerview 和matisse 都导入了recyclerview  一个是support版本的 一个是androidx版本的问题呢

**Comment by REBOOTERS** [comment]
不会，现在最新版本使用的都是 androidx 的 recycleview ,没有别的
