### ISSUE TITLE
如何显示出拍摄视频的按钮去拍摄视频而不是拍摄照片的按钮

### ISSUE THREAD

**Issue by gmfbilu** [zhihu/Matisse#649]
Matisse.from(ThirdCameraFragment.this)
                                               .choose(MimeType.ofVideo())
                                               .showSingleMediaType(true)//只出现视频，排除掉照片
                                               .theme(R.style.Matisse_Dracula)
                                               .countable(false)
                                               .capture(true) //出现拍攝选项
                                               .captureStrategy(new CaptureStrategy(true, "XXXXXX", "test")) 
                                               .addFilter(new GifSizeFilter(320, 320, 5 * Filter.K * Filter.K))
                                               .maxSelectable(9)
                                               .originalEnable(true)
                                               .maxOriginalSize(10)
                                               .imageEngine(new Glide4Engine())
                                               .forResult(REQUEST_CODE_ALBUM);
这样去图库里面选择视频，可是里面还是没有拍摄视频的按钮，出现的是拍摄照片的按钮

**Comment by REBOOTERS** [comment]
只支持调用相机，不区分拍摄视频还是图片。

**Comment by lishiwei** [comment]
这哪行呢。。想拍视频还得重新拍
