### ISSUE TITLE
No super method getLifecycle()Landroidx/lifecycle/Lifecycle; 

### ISSUE THREAD

**Issue by wuxuebai** [zhihu/Matisse#654]
看了下关于这个异常的解决方案 是升级到最新版本的andoridx 但是这个依赖一定要升到1.0.2吗？我现在的项目里还有许多其他的第三方框架依赖  要是改动的话成本实在是太大了

**Comment by REBOOTERS** [comment]
有更详细的日志吗 ？

https://github.com/zhihu/Matisse/issues/new?template=bug_report.md

**Comment by wuxuebai** [comment]
No super method getLifecycle()Landroidx/lifecycle/Lifecycle; 
in class Landroidx/core/app/ComponentActivity; or its super classes (declaration of 'androidx.core.app.ComponentActivity' 
appears in /data/app/com.yishi.carseal-cChKw9kPmCD6WhMh6NOWIA==/base.apk!classes6.dex)

**Comment by wuxuebai** [comment]
implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
implementation 'androidx.annotation:annotation:1.1.0'
annotationProcessor 'androidx.annotation:annotation:1.1.0'
implementation "androidx.constraintlayout:constraintlayout:1.1.3"
implementation 'androidx.multidex:multidex:2.0.0'
implementation 'androidx.legacy:legacy-support-v4:1.0.0'

更新Androidx到最新版本，解决这个问题
--------------------------------------------------
请问如果不更新androidx 到1.1.0能解决这个异常吗？

**Comment by REBOOTERS** [comment]
这个看起来是 androidx 库自身的兼容问题了😳，没有兼容之前的版本。
