### ISSUE TITLE
crash after click take photo

### ISSUE THREAD

**Issue by lbx2015** [zhihu/Matisse#658]
I am using the latest version, 点击拍摄图片崩溃了。怎么弄个的。android studio 3.5
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference

下面是的我配置      Matisse.from(this)
                .choose(MimeType.ofImage())
                .capture(true)
                .captureStrategy(new CaptureStrategy(true, "chef", "chef"))
                .theme(com.zhihu.matisse.R.style.Matisse_Zhihu)
                .countable(true)
                .maxSelectable(3)
//                .addFilter(new GifSizeFilter(320, 320, 5 * Filter.K * Filter.K))
//                .gridExpectedSize(getResources().getDimensionPixelSize(R.dimen.grid_expected_size))
                .restrictOrientation(ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED)
                .thumbnailScale(0.85f)
                .imageEngine(new Glide4Engine())
                .forResult(REQUEST_CODE_CHOOSE);

**Comment by DroidVent** [comment]
@lbx2015 were you able to solve this?

**Comment by REBOOTERS** [comment]
`captureStrategy(new CaptureStrategy(true, "chef", "chef"))`

这个是随便写的吗？😢

**Comment by DroidVent** [comment]
No, i replaced it as below
.captureStrategy(new CaptureStrategy(true, getActivity().getApplicationContext().getPackageName() + ".provider")
