### ISSUE TITLE
平板电脑进入相册点击拍照返回图片列表显示的图片很小

### ISSUE THREAD

**Issue by lixins** [zhihu/Matisse#688]
平板电脑进入相册点击拍照返回图片列表，图片会显示很小，如果拍照返回的图片列表，图片显示很小，后面再进相册选择图片，返回图片列表显示的也是小图片。如果进入相册不点击拍照而是直接选择图片的话，那返回图片列表就显示正常。以上是平板电脑试出来的问题，正常的安卓机不会有这个问题，是我哪里没有使用对吗？

**Comment by REBOOTERS** [comment]
iPai 是啥？@lixins

**Comment by lixins** [comment]
哈哈，好尴尬，华为CMR-W09平板电脑

**Comment by REBOOTERS** [comment]
上代码吧，还有你的的版本什么的麻烦 说清楚。。。

**Comment by lixins** [comment]
package com.csk.realestateplatform.module.me;

import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.Manifest;
import android.content.Intent;
import android.content.pm.ActivityInfo;
import android.graphics.Color;
import android.net.Uri;
import android.nfc.Tag;
import android.os.Bundle;
import android.text.TextUtils;
import android.util.Log;
import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;

import com.chad.library.adapter.base.BaseQuickAdapter;
import com.csk.realestateplatform.R;
import com.csk.realestateplatform.adapter.PictureAdapter;
import com.csk.realestateplatform.base.BaseActivity;
import com.csk.realestateplatform.base.Constant;
import com.csk.realestateplatform.utils.ImageUtils;
import com.csk.realestateplatform.utils.StringUtil;
import com.csk.realestateplatform.utils.ToastUtil;
import com.tbruyelle.rxpermissions2.RxPermissions;
import com.wuhenzhizao.titlebar.widget.CommonTitleBar;
import com.zhihu.matisse.Matisse;
import com.zhihu.matisse.MimeType;
import com.zhihu.matisse.engine.impl.GlideEngine;
import com.zhihu.matisse.internal.entity.CaptureStrategy;
import com.zhy.view.flowlayout.FlowLayout;
import com.zhy.view.flowlayout.TagAdapter;
import com.zhy.view.flowlayout.TagFlowLayout;

import java.util.ArrayList;
import java.util.List;

import butterknife.BindView;
import io.reactivex.functions.Consumer;

public class PublishHouseActivity extends BaseActivity  {


    @BindView(R.id.rv_indoor_figure)
    RecyclerView rv_indoor_figure;

    private PictureAdapter pictureAdapter;

    private int SelectMax = 15;//图片最大选择数量

    private List<String> pictureList = new ArrayList<>();

    @Override
    public int getLayoutResId() {
        return R.layout.activity_publish_house;
    }

    @Override
    public void initVariable() {
    }

    @Override
    public void initView() {
    
        initAdapter();

    }


    /**
     * 初始化图片列表
     */
    private void initAdapter() {

        rv_indoor_figure.setLayoutManager(new GridLayoutManager(this, 3));
        pictureAdapter = new PictureAdapter(R.layout.item_picture_layout, pictureList, onAddPicClickListener);
        pictureAdapter.setSelectMax(SelectMax);
        rv_indoor_figure.setAdapter(pictureAdapter);

        pictureAdapter.setOnItemChildClickListener(new BaseQuickAdapter.OnItemChildClickListener() {
            @Override
            public void onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
                switch (view.getId()) {
                    case R.id.ll_del:
                        pictureAdapter.remove(position);
                        setTextViewColor(tv_indoor_figure_number);
                        break;
                }
            }
        });
    }

    private PictureAdapter.onAddPicClickListener onAddPicClickListener = new PictureAdapter.onAddPicClickListener() {
        @Override
        public void onAddPicClick() {
            selectImage();
        }
    };

    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == Constant.REQUEST_CODE_CHOOSE && resultCode == RESULT_OK) {
            //图片路径 同样视频地址也是这个 根据requestCode
            List<String> pathList = Matisse.obtainPathResult(data);
            pictureList.addAll(pathList);
            pictureAdapter.setNewData(pictureList);

            setTextViewColor(tv_indoor_figure_number);

        }
    }

    /**
     * 进入相册进行图片选择
     */
    private void selectImage() {

        RxPermissions rxPermissions = new RxPermissions(this);
        rxPermissions.request(Manifest.permission.READ_EXTERNAL_STORAGE, Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.CAMERA).subscribe(new Consumer<Boolean>() {
            @Override
            public void accept(Boolean aBoolean) throws Exception {

                if (aBoolean) {
                    Matisse.from(PublishHouseActivity.this)
                            .choose(MimeType.ofImage())
                            .maxSelectable(SelectMax - pictureList.size())
                            //选择照片时，是否显示拍照
                            .capture(true)
                            //参数1 true表示拍照存储在共有目录，false表示存储在私有目录；参数2与 AndroidManifest中authorities值相同，用于适配7.0系统 必须设置
                            .captureStrategy(new CaptureStrategy(true, "com.csk.realestateplatform.fileprovider"))
                            //有序选择图片 123456...
                            .countable(true)
                            //选择方向
                            .restrictOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT)
                            //界面中缩略图的质量
                            .thumbnailScale(0.8f)
                            //蓝色主题
                            .theme(R.style.Matisse_Zhihu)
                            //Glide加载方式
                            .imageEngine(new GlideEngine())
                            //请求码
                            .forResult(Constant.REQUEST_CODE_CHOOSE);

                } else {
                    ToastUtil.showMessage(PublishHouseActivity.this, "未授权权限，部分功能不能使用");
                }

            }
        });


    }
}

**Comment by lixins** [comment]
package com.csk.realestateplatform.adapter;

import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.bumptech.glide.Glide;
import com.chad.library.adapter.base.BaseQuickAdapter;
import com.chad.library.adapter.base.BaseViewHolder;
import com.csk.realestateplatform.R;

import java.util.ArrayList;
import java.util.List;

public class PictureAdapter extends BaseQuickAdapter<String, BaseViewHolder> {

    public static final int TYPE_CAMERA = 1;
    public static final int TYPE_PICTURE = 2;
    private List<String> data;
    private int selectMax;

    /**
     * 点击添加图片跳转
     */
    private onAddPicClickListener mOnAddPicClickListener;

    public interface onAddPicClickListener {
        void onAddPicClick();
    }

    public PictureAdapter(int layoutResId, @Nullable List<String> data, onAddPicClickListener mOnAddPicClickListener) {
        super(layoutResId, data);
        this.data = data;
        this.mOnAddPicClickListener = mOnAddPicClickListener;
    }

    @Override
    public int getItemCount() {

        if (data.size() < selectMax) {
            return data.size() + 1;
        } else {
            return data.size();
        }
    }

    @Override
    public int getItemViewType(int position) {
        if (isShowAddItem(position)) {
            return TYPE_CAMERA;
        } else {
            return TYPE_PICTURE;
        }
    }

    private boolean isShowAddItem(int position) {
        int size = data.size() == 0 ? 0 : data.size();
        return position == size;
    }

    public void setSelectMax(int selectMax) {
        this.selectMax = selectMax;
    }

    @Override
    protected void convert(@NonNull BaseViewHolder helper, String item) {

        ImageView fiv = helper.getView(R.id.fiv);
        LinearLayout ll_del = helper.getView(R.id.ll_del);
        //少于最大限制数量，显示继续添加的图标
        if (getItemViewType(helper.getAdapterPosition()) == TYPE_CAMERA) {

            Glide.with(mContext).load(mContext.getResources().getDrawable(R.mipmap.add_images)).into(fiv);
            fiv.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {
                    mOnAddPicClickListener.onAddPicClick();
                }
            });
            ll_del.setVisibility(View.INVISIBLE);
        } else {
            ll_del.setVisibility(View.VISIBLE);
            Glide.with(mContext).load(item).into(fiv);
        }

        helper.addOnClickListener(R.id.ll_del);

    }
}

**Comment by lixins** [comment]
框架版本 V0.5.3-beta3

**Comment by lixins** [comment]
如果我进入相册点击拍照，返回图片列表显示的是小图，然后我再进入相册一张一张的去选择照片返回图片显示列表，选着选着，第一张图就又显示正常了

**Comment by REBOOTERS** [comment]
不明白你在说啥？
