### ISSUE TITLE
能否只需要显示图片

### ISSUE THREAD

**Issue by ConDey** [zhihu/Matisse#71]
新的0.5.2这个版本，我只能设置是选择图片还是视频，但是我希望用户只能看到图片或者视频，这个应该怎么处理

**Comment by gejiaheng** [comment]
@ConDey Do you mean v0.5.0-alpha2? This is not supported now. It may be supported in the future, but I'm not sure about it.

**Comment by ConDey** [comment]
@gejiaheng  这个非常重要！麻烦你尽快更新一下把，另外还有一个问题，任何一个版本都没有你在源码当中新增的Matisse.obtainPathResult(Intent intent)这个方法，我现在非常需要这个方法，麻烦发布一个新的版本来支持这个方法吧。

**Comment by gejiaheng** [comment]
@ConDey 
You can find `Matisse.obtainPathResult()` in the latest version 0.5.0-alpha3.   
As for the feature request this issue asks for, sorry I don't have time. You can modify the source code or contribute to the project if you really need it.
