### ISSUE TITLE
Any way to change the language of buttons?

### ISSUE THREAD

**Issue by bruferrari** [zhihu/Matisse#72]
Hi, I would like to use Matisse on a project that I'm woking on but I've noticed that this lib doesn't have support to another languages other than english, is it right? is there a way to achieve it?

**Comment by coderkan** [comment]
For Turkish language , I can contribute .

**Comment by gejiaheng** [comment]
@bruferrari 
Matisse now supports 3 languages:
1. English (values/strings.xml)
2. Simplified Chinese (values-zh/strings.xml)
3. Taiwan Traditional Chinese (values-zh-rTW/strings.xml) 

And as @coderkan mentioned above, anyone can contribute.

As an example, you can check out https://github.com/zhihu/Matisse/pull/45.

**Comment by bruferrari** [comment]
Ok, thanks for the answer, that's what I thought so, I'll contribute with the translation to Brazilian Portuguese.

**Comment by gejiaheng** [comment]
@bruferrari 
Thanks in advance!
