### ISSUE TITLE
怎么获取图片的绝对路径？

### ISSUE THREAD

**Issue by woniu0936** [zhihu/Matisse#73]
我使用的时候，发现根据Uri获取到的图片路径不能生成正确的file，FIie file = new File(uri.getPath());生成的这个file上传给服务器的时候报的路径不对

**Comment by nekocode** [comment]
See [here](https://github.com/zhihu/Matisse/issues/49).

**Comment by woniu0936** [comment]
我看到你们的代码里面已经有这个api了，希望在下个版本里面能提供，感谢！

**Comment by gejiaheng** [comment]
@woniu0936 We will!

**Comment by gejiaheng** [comment]
@woniu0936 Please check out the latest version 0.5.0-alpha3

**Comment by woniu0936** [comment]
cool!

**Comment by ConanHolmes** [comment]
@woniu0936 你好，现在怎么把 0.5.0-alpha3添加到项目中使用啊？我现在就是在gradle中写compile 'com.zhihu.android:matisse:0.4.3'这句话，但是没有获取绝对路径的api...能否告知？相当感谢==

**Comment by ConanHolmes** [comment]
@woniu0936 好了  谢谢了..我解决了==感觉自己好蠢啊
