### ISSUE TITLE
从微信下载的图片没有显示在最前面

### ISSUE THREAD

**Issue by EdwardCheck** [zhihu/Matisse#740]
老铁们有没有遇到从微信下载的图片咋一看以为不显示，单选微信里的图片发现穿插在中间了，而不是列表最前面。有知道怎么修改的吗？

**Comment by toutoumu** [comment]
呵呵

**Comment by EdwardCheck** [comment]
只能RDTFSC了
将AlbumLoader和AlbumMediaLoader里的ORDER_BY改成按修改时间排序
`private static final String ORDER_BY = MediaStore.Images.Media.DATE_MODIFIED + " DESC";`

**Comment by fengpenpao** [comment]
然后并没有什么用
