### ISSUE TITLE
代码混淆后，在android 10上图片选择列表没有内容

### ISSUE THREAD

**Issue by erichyx** [zhihu/Matisse#752]
用最新的0.5.3-beta3，项目开启了混淆，在android 10上运行的时候，图片列表没有内容，连拍照的那个图标都没有出现。在android10之前的系统运行，没出现此问题。

![image](https://user-images.githubusercontent.com/10595445/75641663-f2a33c80-5c73-11ea-8bb7-2430742b1282.png)

**Comment by LuoboDcom** [comment]
@erichyx 你解决了吗？

**Comment by erichyx** [comment]
@LuoboDcom 没解决。

**Comment by LuoboDcom** [comment]
我也看到我debug包可以加载，release不能。我查了下，发现loader不执行




| |
乐山
邮箱：yueshan0607@163.com
|

签名由 网易邮箱大师 定制

在2020年03月25日 18:23，erichyx 写道：

@LuoboDcom 没解决。

**Comment by erichyx** [comment]
@LuoboDcom 你项目是不是也有配置代码混淆？

**Comment by LuoboDcom** [comment]
有配置混淆，但我现在把相册抽成module，设置release不混淆也没用，不会加载出来




| |
乐山
邮箱：yueshan0607@163.com
|

签名由 网易邮箱大师 定制

在2020年03月25日 18:34，erichyx 写道：

@LuoboDcom 你项目是不是也有配置代码混淆？

**Comment by LuoboDcom** [comment]
解决了哦，升级依赖的LifeCycle库，我现在是2.2.0版




| |
乐山
邮箱：yueshan0607@163.com
|

签名由 网易邮箱大师 定制

在2020年03月25日 19:18，yoosir 写道：
有配置混淆，但我现在把相册抽成module，设置release不混淆也没用，不会加载出来




| |
乐山
邮箱：yueshan0607@163.com
|

签名由 网易邮箱大师 定制

在2020年03月25日 18:34，erichyx 写道：

@LuoboDcom 你项目是不是也有配置代码混淆？

**Comment by erichyx** [comment]
@LuoboDcom 多谢，我之前用的2.2.0是alpha版本，现在改成正式版可以了。
