### ISSUE TITLE
是否考虑单独的选了类型时，只将当前的类型展示出来，而不是视频、图片都显示出来，再在点击非选择类型时，提示不支持的类型？

### ISSUE THREAD

**Issue by LJW123** [zhihu/Matisse#754]
是否考虑单独的选了类型时，只将当前的类型展示出来，而不是视频、图片都显示出来，再在点击非选择类型时，提示不支持的类型

**Comment by ykl522** [comment]
showSingleMediaType(true) 搭配 choose(MimeType.ofVideo())
choose里面是什么类型，就只展示什么类型

**Comment by LJW123** [comment]
> showSingleMediaType(true) 搭配 choose(MimeType.ofVideo())
> choose里面是什么类型，就只展示什么类型

非常感谢
