### ISSUE TITLE
Preview mode apply text color

### ISSUE THREAD

**Issue by DummyCo** [zhihu/Matisse#76]
Seems like there is no text color customization for preview mode apply text via attrs
`bottomToolbar.apply.textColor`
That one isn't applied for suggested property.
Thank you.

**Comment by gejiaheng** [comment]
@DummyCo 
I thought it was not necessary to customize **Back** and **Apply** button text, because the page background is black. But you can contribute if you want this feature. And if you do contribute, differ buttons on different UI cause they have different background colors.
