### ISSUE TITLE
选择图片列表显示空白

### ISSUE THREAD

**Issue by leviluo** [zhihu/Matisse#876]
![Screenshot_2022-04-18-13-40-50-310_tech nani www](https://user-images.githubusercontent.com/19730473/163760779-d3c7f107-ed4b-42f8-81e2-5c004fe3e6a2.jpg)
![Screenshot_2022-04-18-13-40-54-055_tech nani www](https://user-images.githubusercontent.com/19730473/163760786-43d6715f-f14c-41bb-8b60-6e91b4d56316.jpg)

明明有图片，左上角选择图片之后，为什么就显示空白了？

**Comment by leviluo** [comment]
implementation 'androidx.appcompat:appcompat:1.3.1' 用的是最新版

**Comment by leviluo** [comment]
<img width="934" alt="截屏2022-04-18 下午3 10 48" src="https://user-images.githubusercontent.com/19730473/163770608-6e1b1523-e6ee-447e-990b-147a7ef1ad2b.png">
该方法无效
implementation 'androidx.appcompat:appcompat:1.3.1' 用的是最新版，也没有效果

**Comment by dalingge** [comment]
是因为Fragment1.2.0 会等到退出动画、退出框架转换和退出 AndroidX 转换完成后再调用 onDestroyView()。

**Comment by CCTV-11** [comment]
我也遇到这个问题，怎么解决的

**Comment by as1006** [comment]
调试了一下，是时序问题。fragment1.1.0的时候，会先调用前一个MediaSelectionFragment的destroy，再调用后一个MediaSelectionFragment的create相关逻辑。在fragment后续的版本中不会。导致了这个问题，可以使用androidx.fragment:fragment1.1.0。但是这个组件有bug，要兼容。能不能早点升级

**Comment by REBOOTERS** [comment]
please try [https://github.com/REBOOTERS/Matisse/releases](https://github.com/REBOOTERS/Matisse/releases)

**Comment by qqww-1234** [comment]
问下你们最后怎么解决的，appcompat 升级到1.1.0还是没用啊

**Comment by FrankLove** [comment]
@REBOOTERS 0.5.3 it seems also have this bug

**Comment by REBOOTERS** [comment]
> @REBOOTERS 0.5.3 it seems also have this bug

would you like to provide some details about the issue ,pls

**Comment by FrankLove** [comment]
@REBOOTERS  sorry I don't use the source code to test, So can't provide details to you ,If you can test it with a demo,you will find this problem and see details ,if you can fix this bug we all hope to see it
