### ISSUE TITLE
建议，不要指定图片加载框架

### ISSUE THREAD

**Issue by yaozs** [zhihu/Matisse#9]
提供接口，让用户自己选择，这样定制的会更好
比如https://github.com/yaozs/ImageShowPicker/blob/master/imageshowpickerview/src/main/java/com/yzs/imageshowpickerview/ImageLoaderInterface.java，这样写

**Comment by gejiaheng** [comment]
@yaozs 
Actually what Matisse provide is just a image loading interface as the link you posted.

https://github.com/zhihu/Matisse/blob/master/matisse/src/main/java/com/zhihu/matisse/engine/ImageEngine.java

And you can read our wiki about this feature: https://github.com/zhihu/Matisse/wiki/Image-Engine
